### ISSUE TITLE
Snackbar / Error Handling Issue

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#102]
![image](https://user-images.githubusercontent.com/11256376/85179443-a1f53500-b29e-11ea-91be-7b3e675f25ba.png)

Steps to reproduce,

1) Go to dev.simplq.me
2) If you have not done before, clear localstorage once so that recent auth changes don't cause problems.
3) Turn off internet. Then try creating a queue

Expected: A snackbar to tell the user that he/she is offline.

**Comment by maaverik** [comment]
Fix added to latest PR
