### ISSUE TITLE
Fix the problem with the lint workflow

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#115]
The lint workflow set up using github actions fails saying eslint is not installed even though eslint is part of package.json. Use this for reference https://github.com/samuelmeuli/lint-action.

**Comment by daltonfury42** [comment]
Done. Let it run for some time. When we are confident it's working, let's add it as a branch protection rule.

But I'm not sure if it will work when someone sends a PR from a fork.
