### ISSUE TITLE
Add images and stepper transitions to home page

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#116]
The home page in the new design (https://xd.adobe.com/view/5b8cc4d6-174a-48f4-53fa-5088ed723862-2dbd/) uses images from https://undraw.co/illustrations. Find the required images and add them to the homepage along with the steppers for the how-to-join and how-to-create sections. Get the latest code either from master or new-frontend and add on top.

**Comment by daltonfury42** [comment]
For the stepper, I found this, shall I give it a try?

https://www.youtube.com/watch?v=N7W-S4JhMXY

@maaverik @thehamzarocks

**Comment by maaverik** [comment]
Seems like a ton of work. I was thinking of modifying this a bit and get something close to the design: https://material-ui.com/components/steppers/#text-with-carousel-effect. It seems like it'll be much easier and won't bloat the codebase too much.

**Comment by daltonfury42** [comment]
Done
