### ISSUE TITLE
[Design] Show User's personal details on waiting page.

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-frontend#125]
Right now, the waiting page is very generic. As discussed with @daltonfury42, Having at least the user's name on the page might be a good touch. Can discuss what exactly we need to show on the waiting page.

**Comment by akashkbaburajan** [comment]
![Adobe XD 27-09-2020 12_44_55](https://user-images.githubusercontent.com/16539463/94358570-b330b780-00bf-11eb-817e-0372f7e9a369.png)
incorporated this idea in new design
