### ISSUE TITLE
User-Friendly message when the token has been deleted

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-frontend#131]
Currently, when the user is deleted from the queue, he receives an error saying "the token has been deleted".

We should have a clearer message, or even change the display to something other than the notified one.

**Comment by daltonfury42** [comment]
For now, the UI is blindly displaying the response from backend. Let's keep this open, and once the new UI is done, we should find out how to handle this properly.

Rough idea, we from the backend can return proper error codes, and the UI would have to display the human friendly text. What do you think?

**Comment by maaverik** [comment]
I think this can be closed now since we are displaying a better message in the queue status page.
