### ISSUE TITLE
Add sidebar

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#136]
Create sidebar as shown in the design: https://xd.adobe.com/view/5b8cc4d6-174a-48f4-53fa-5088ed723862-2dbd/screen/55f12f5b-017e-4391-8fbe-ef35ba56a8bc/

**Comment by MehmetFiratKomurcu** [comment]
Hey @maaverik , I'm trying to do this issue but I'm stuck with somewhere. I created a PR for you to detect my fault. Could you review and help me what is the problem? Thanks.

**Comment by daltonfury42** [comment]
@m
