### ISSUE TITLE
[Design] Contact Us section in app

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-frontend#147]
Allowing potential users to reach out to us with their requirements would increase outreach.

People would be able to find SimplQ on social media/ other forums and try it out for themselves. If they felt anything could be done to make it better for their use case, they could reach out to us for collaboration.

Let's have a "Contact Us" section and make it clear to potential users that we're ready to collaborate with them.

**Comment by daltonfury42** [comment]
How should we allow people to contact us? Will giving our personal email somewhere help? If we give one of our email id, will people / bots spam us?

**Comment by daltonfury42** [comment]
I'd prefer people be send to "https://github.com/SimplQ/simplQ-frontend/issues/new", for example, we can write somewhere,

For comments, feedbacks or bugs reach us [here](https://github.com/SimplQ/simplQ-frontend/issues/new).

cc @raima-zachariah @akashkbaburajan

**Comment by daltonfury42** [comment]
Downside of this is that the reporter should have a github account. But what is the next best easiest way to get non-tech people to give feedback?

**Comment by maaverik** [comment]
How about we make a new email account for just this purpose and have that account forward the mails to each of us so that atleast one of us could respond. This way all of us would stay informed too.

**Comment by daltonfury42** [comment]
yes, lets do this...

**Comment by daltonfury42** [comment]
cc: @akashkbaburajan

**Comment by maaverik** [comment]
How about we make one? No point delaying it. What's your opinion on simplq.support@gmail.com?

**Comment by daltonfury42** [comment]
simplq@gmail.com is taken?

**Comment by maaverik** [comment]
Yeah, it's taken already

**Comment by daltonfury42** [comment]
@maaverik is this email ID created?

**Comment by maaverik** [comment]
Not yet. Which one do we want? Gmail doesn't seem to allow words like support or admin in the email ids anymore.

**Comment by daltonfury42** [comment]
Anything is fine with me

**Comment by maaverik** [comment]
How about just team.simplq@gmail.com?

**Comment by daltonfury42** [comment]
Yeah, looks decent

**Comment by maaverik** [comment]
It's created.

**Comment by daltonfury42** [comment]
I created the email contact@simplq.me I'll send a request, to add you also into the forwarding list

**Comment by daltonfury42** [comment]
@sajmalyousef We should add a google form / something similar that we were talking about. I'm thinking a "Contact Us" link in the footer under the "Keep in touch" section:

![image](https://user-images.githubusercontent.com/11256376/94833538-dd220b00-042c-11eb-807f-c4243a08155f.png)


The form should be very simple, with a title/description email id and a textbox on what they want to contact us about.

We should get an email alert when someone fills the form. (Google Forms does this)
