### ISSUE TITLE
Give Material Like ripple effect to buttons

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#153]
https://codepen.io/finnhvman/pen/jLXKJw

we should try this, looking nice. Then we can remove the blue ugly border which comes on focus:

![image](https://user-images.githubusercontent.com/11256376/89076110-58b7fb00-d39d-11ea-9b23-9e04543bc720.png)

**Comment by jithinlal** [comment]
I'll do this

**Comment by jithinlal** [comment]
The primary color seems to be #3a3768, can we change this into #776fff ?

That seems to be the image color used throughout the app.

**Comment by sajmalyousef** [comment]
Should'nt "share queue" be changed to "Share" , since refresh is just "refresh" and not refresh queue?

**Comment by maaverik** [comment]
Hi @jithinlal, this is the design we're following: https://xd.adobe.com/view/5b8cc4d6-174a-48f4-53fa-5088ed723862-2dbd/grid. Two colors are used throughout, #3A3768 for dark and #6C63FF with opacity 20% for light. So, what did you mean by #776fff being used? I think we've used just these two everywhere.

**Comment by maaverik** [comment]
@sajmalyousef You're right. By the end, it should look like this, so we just need to get there.
![Screenshot from 2020-08-18 23-01-58](https://user-images.githubusercontent.com/12583528/90545885-ede12f00-e1a6-11ea-9f36-259db68af7ef.png)

**Comment by jithinlal** [comment]
@maaverik what i meant is that, the color of the images used below your home page is #776fff, if we could include that as the color, the ripple effect will be pronounced and all.
![2020-08-18_22-58](https://user-images.githubusercontent.com/9658385/90546203-5e884b80-e1a7-11ea-919e-fa6b0906d484.png)

**Comment by jithinlal** [comment]
@maaverik it was just a thought, nm

**Comment by jithinlal** [comment]
Created a PR request that included the ripple, can you look into that ?

**Comment by maaverik** [comment]
We're thinking of sticking to the design we have right now. So at least for now, we'll leave the color as it is.

**Comment by daltonfury42** [comment]
@jithinlal the color looks a bit too bright, in my opinion. Can you try changing the ripple colour instead to see if helps on the dark button?

**Comment by jithinlal** [comment]
@daltonfury42 you talking about the color when hovered? The rippling effect is not seen on the home page, since the page navigation is happening pretty fast, but it could be seen on the create queue page though
