### ISSUE TITLE
[Bug] Home Page Slider Should Preload the SVGs

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#154]

**Comment by maaverik** [comment]
Could you describe the exact issue? I'd like to try this one.

**Comment by daltonfury42** [comment]
This is a very nitty-gritty thing I had noticed. If you load the homepage, and then clear the network calls hostory,
![image](https://user-images.githubusercontent.com/11256376/89973454-fbb22400-dc7d-11ea-9d71-bfe23a08500a.png)

Then move the slider, you'll see that the images are loaded on demand:
![image](https://user-images.githubusercontent.com/11256376/89973527-2d2aef80-dc7e-11ea-9159-15ecf17cf141.png)

I thought it would be nice to pre-load it on page load itself. Otherwise on slow internet, till the image gets downloaded, you'll get a while blank region. I wanted to explore if this is possible later, so created an issue.
