### ISSUE TITLE
Fix error boundary

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#161]
The error boundary which is set up does not work for some reason and needs investigation and possible rework. It's in https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/ErrorHandler.jsx

**Comment by daltonfury42** [comment]
Also we can use an axios interceptor to handle api call errors in one place: https://stackoverflow.com/questions/48990632/how-to-manage-axios-errors-globally-or-from-one-point

**Comment by daltonfury42** [comment]
I've also noticed that ErrorBoundary is a class component, and inside it we are using `useDispatch`. Hooks can be used only from functional components. Can we also rewrite error boundary as a functional component?

**Comment by maaverik** [comment]
I'm not sure if it's possible to make it functional since the docs don't have a functional version for it. Will do some research. You might be right about the useDispatch, but the reason for the error boundary failing is something else I think, since the useDispatch is only for showing the error popup and not really required in the boundary. I think I added it to debug the boundary failure.

**Comment by daltonfury42** [comment]
This is just a clue/theory... I think the error bountary code is fine, but someone else is catching the error before it reaches your code... Is the exception coming on console?

**Comment by maaverik** [comment]
Well, the exception wasn't caught anywhere, the page itself used to crash which is exactly what the boundary should take care of. I forgot how I tested it, so will have to check again.

**Comment by skShekhar** [comment]
@maaverik The issue might be with [PageNotFound](https://github.com/SimplQ/simplQ-frontend/blob/77542746b5e5c211fadbaec84827b7492bbab1a1/simplq/src/components/pages/PageNotFound/index.jsx#L8) component. It will crash if `match/params` is undefined. I'm able to see the fallback UI if I remove this check.

But I'm not sure since this issue was created before the if-check code was merged in.

**Comment by maaverik** [comment]
Hey @skShekhar, I just took a look. You're right about pageNotFound, it will cause a crash the way it's defined in ErrorHandler. I'll add some optional chaining in the condition to fix that. Good catch.

But for me, the error boundary still doesn't work right. I messed up some code on purpose in the homepage to test, and while it was going to the 404 page just fine, a few seconds later, the exception it was supposed to catch popped up on screen. Is that not happening to you?

**Comment by skShekhar** [comment]
@maaverik Yes I'm seeing the stack trace. Are you not getting the 404 page once you dismiss it? Or maybe might have missed out `props.match.params.queueName` at line 18.

**Comment by maaverik** [comment]
Okay, I always thought since the stack trace was showing up, the error boundary wasn't working correctly. It intentionally shows the trace in development to help with debugging ([ref](https://stackoverflow.com/questions/52096804/react-still-showing-errors-after-catching-with-errorboundary)). Thanks for pointing it out @skShekhar, this has been a mystery to me for a long time, turns out it was always working fine :smile:.
