### ISSUE TITLE
Move notification logic to notification service

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#165]
if possible

**Comment by jithinlal** [comment]
where is this located on the code ?

**Comment by maaverik** [comment]
The code is referenced in this PR: https://github.com/SimplQ/simplQ-frontend/pull/132/files. @daltonfury42, could you elaborate on what you mean exactly here?

**Comment by maaverik** [comment]
https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/common/NotificationButton.jsx this is the main file with the logic. It's supposed to be used in the queue status page for the queue members to be notified, but I don't see it being used there right now. @thehamzarocks @daltonfury42, did we remove it by accident or was there a reason it was removed?

**Comment by daltonfury42** [comment]
I didn't intentionally move it... @thehamzarocks was also asking... so it was removed by mistake... for this task, I can give a rough idea now, but if a more detailed design is required,  I'll take a look during the weekend.

Basic idea is, we would be better off creating a NotificationService outside of react, which exposes two functions:

1) askUserForPermission() -> Asks for permission if permission was not asked before
2) showNotification(title, text) -> Show a notification if the user has allowed notifications

This is a refactoring task, the idea is, the notification logic is non-presentational, and moving it to a common place would allow us to reuse them in different places... for example, we would want to send notification from admin page as well

**Comment by maaverik** [comment]
Okay, I'll add it back. Maybe I removed it by accident when I refactored the status pages.

**Comment by maaverik** [comment]
@jithinlal If this doesn't seem interesting to you, you could look at #150. It's a relatively tougher task, but you could start doing small parts of it.

**Comment by daltonfury42** [comment]
Raised https://github.com/SimplQ/simplQ-frontend/pull/428 to address this
