### ISSUE TITLE
Tweak Home Page CSS of SimlQ explained components

### ISSUE THREAD

**Issue by akashkbaburajan** [SimplQ/simplQ-frontend#168]
Currently in new.simplq.me the "Create a Queue at the click of a button" and "Join a queue without being there" components are positioned top and bottom. It would be nice to have them side by side on a wider screen but top and bottom on a smaller screen.
![Screenshot (9)](https://user-images.githubusercontent.com/16539463/89731120-32135780-da62-11ea-83cc-eaf8175e2f86.png)
![Screenshot (10)](https://user-images.githubusercontent.com/16539463/89731121-35a6de80-da62-11ea-8d76-afed80b13c33.png)

**Comment by daltonfury42** [comment]
Hmm. We should do something of that lines... sizing, padding etc on home page should be changed.  One thing is, two steppers side by side would look a little odd.
