### ISSUE TITLE
Styling our expansion panel

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#171]
One independent task to take up would styling the "Add Manually" expansion panel:

![image](https://user-images.githubusercontent.com/11256376/90474291-95784600-e142-11ea-84dc-6093c8afffdf.png)

Design: https://xd.adobe.com/view/5b8cc4d6-174a-48f4-53fa-5088ed723862-2dbd/screen/9d04ccf4-6738-477b-a1a1-73e3ecba47c5/

The expansion panel would be a generic component that we can then reuse at other places, and so it should lie in the `components/common` folder

**Comment by jithinlal** [comment]
created a PR on this. Please check.
