### ISSUE TITLE
Exposing amplify config info

### ISSUE THREAD

**Issue by jithinlal** [SimplQ/simplQ-frontend#172]
Is it okay to expose amplify cloud details including AmplifyAppId in the back-end folder ?

**Comment by maaverik** [comment]
Hi, which file and details are you talking about in https://github.com/SimplQ/simplQ-frontend/tree/new-frontend/simplq/amplify/backend? @daltonfury42  and @thehamzarocks, do you guys know if the App Id is safe to expose?

**Comment by daltonfury42** [comment]
I want to investigate in the weekend. amplify-cli generated a .gitignore on it's own, also, when we were setting this up for you, you needed credentials... so I thought things are secure... I'll take a look

**Comment by jithinlal** [comment]
https://github.com/aws-amplify/amplify-cli/issues/1032

based on this issue, it's okay, but needs to make sure

**Comment by daltonfury42** [comment]
Just noticed today that AmplifyAppId is already exposed by amplify in autogenerated urls when you have not configured a domain name:

![image](https://user-images.githubusercontent.com/11256376/93028373-34546d00-f631-11ea-89f0-f8f0df031095.png)


So I guess it's safe to make it public.
