### ISSUE TITLE
[Design ] Announcements to be shared with queue users 

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#176]
An incremental feature to the custom form feature wherein, the queue creator can notify some common details to all the queue users .
1.
**Given**
A shopkeeper has not created a queue 

***When ***
He creates a queue and also wants to make an announcement (Specific offer ) to everyone who joins the queue 

***Then***
Anyone opening the join queue link should be able to see the announcement , the admin dashboard should have the capability to edit/delete this 

2.

**Given**
A shopkeeper has created a  queue and there are people in the queue 

***When ***
He wants to make an announcement (Specific offer ) to everyone who is in the queue/ who joins the queue later on 

***Then***
Anyone opening the queue link should be able to see the announcement

**Comment by daltonfury42** [comment]
We would need let the queue owner set a small and optional queue description, which will be shown when someone is in the joining page. Like google forms.

But your proposal is a bit more that this. Can you come up with real life usecases where a shopkeeper gives frequent offers... I don't think a lot of shops will find this "general announcement" feature useful.

**Comment by daltonfury42** [comment]
We will do this if we ever get a customer and we see it adding some value to the customer
