### ISSUE TITLE
Add manually button not working on the create queue page.

### ISSUE THREAD

**Issue by jithinlal** [SimplQ/simplQ-frontend#178]
Seems like the add manually button below the create queue page is useless. Not able to add a number or a name

**Comment by daltonfury42** [comment]
Yes, we have not completed this yet. This is one task.

**Comment by jithinlal** [comment]
@daltonfury42 , i have fixed this bug for now, and I will try to make this into a common component. But please merge my older PR or reject it, so that I can create another PR for this one

**Comment by maaverik** [comment]
This has been fixed now.
