### ISSUE TITLE
[Design] Notifications button placement

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#180]
Right now, I've placed the notification button below the status container. The refresh and queue buttons will be removed soon following the design, but where should we place the notification button. It need not be a button either, we just need to show an option that the user intuitively understands.

![Screenshot from 2020-08-19 23-25-33](https://user-images.githubusercontent.com/12583528/90673311-3109d380-e275-11ea-992e-25a52e9ffa9d.png)
![Screenshot from 2020-08-19 23-25-42](https://user-images.githubusercontent.com/12583528/90673358-40891c80-e275-11ea-912c-83eda5a2725e.png)

**Comment by akashkbaburajan** [comment]
![Adobe XD 27-09-2020 12_44_55](https://user-images.githubusercontent.com/16539463/94358516-49181280-00bf-11eb-9192-3ac46c0e9c71.png)
The updated design takes care of that. has a nice toggle option for enabling or disabling notification.

**Comment by maaverik** [comment]
Closing as duplicate of #291
