### ISSUE TITLE
Call Facility From Admin Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#184]
We are not letting the admin call the user... we should have a call button, I feel.. like the the old UI..

The privacy concern that Edwin had raised, I feel we can ignore for now... what do you think?

**Comment by akashkbaburajan** [comment]
Yes, I agree. This will need a new design of the User Tile on Queue Admin page. I have made a new one with the following things in mind:
1. It should not be cluttered.
2. It should have all the basic functionalities that we need -> Call, Notify, Delete

The different states of old user tile.
![Old User Tile](https://user-images.githubusercontent.com/16539463/91636848-7373a300-ea21-11ea-9880-7a7ce045835e.png)

The new user tile.
![New User Tile](https://user-images.githubusercontent.com/16539463/91636852-81292880-ea21-11ea-9927-ec45d62444fa.png)

**Comment by navaneeth-spotnana** [comment]
This is really nice.. especially the rearrangement involving the token number.

I'm not a big fan of our "x" button. Keeping it inside the tile will keep it cluttered.. can we somehow keep it outside and bigger, what do you think?

**Comment by akashkbaburajan** [comment]
Awesome, a little bigger "X" button is doable 👍

**Comment by daltonfury42** [comment]
Can we have a 90 degree rotated remove notch like this (rough diagram) on the right side of the tile:

![IMG_20200829_191543](https://user-images.githubusercontent.com/11256376/91638345-95beee00-ea2c-11ea-9928-aa9e9700d5e4.jpg)

Of some different color but not too bright..
