### ISSUE TITLE
Queue history for admin

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#187]
A log of the history of the queue has to be added in the admin page: https://xd.adobe.com/view/5b8cc4d6-174a-48f4-53fa-5088ed723862-2dbd/screen/2fbb3e31-1e3a-4eab-ac2f-7d7f2247f6b3/specs/

**Comment by daltonfury42** [comment]
Let's revisit this feature after we implement the new design. I think this is a feature we can build at the end, once the core features are done. What do you say?
