### ISSUE TITLE
Format the phoneInput component

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#190]
The flag in the phoneInput component in the join page is messed up. Adding an arbitrary padding value to the exact dropdown button fixes it in the dev tools panel, but getting the right class to add it in the code is tricky.

Also, the border color is wrong. I'd also prefer the phone input heading to be removed.

**Comment by lukigarazus** [comment]
I guess this issue is no longer valid?
![Screenshot from 2020-09-25 08-20-38](https://user-images.githubusercontent.com/32484818/94233857-e250f880-ff08-11ea-8440-6a1d0d141ec7.png)

**Comment by daltonfury42** [comment]
Hi @lukigarazus we ran out of ready to take issues over last few days. This task is better taken after we have the basic admin page layout done. The weekend is here, and we will plan the admin page and create the next bunch of tasks.

This is a priority task to that we need to take up https://github.com/SimplQ/simplQ-frontend/issues/193 Do you want to take this up in the meantime?

**Comment by maaverik** [comment]
Being looked into in  #298

**Comment by daltonfury42** [comment]
I think the issue was fixed automatically. might be some flex non flex thingy
