### ISSUE TITLE
Style the 404 Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#193]
Add a link to report the issue on github too, in addition to a nice 404 page

**Comment by rohitjethoe** [comment]
Hi @daltonfury42 , I could work on this issue.

**Comment by maaverik** [comment]
Sure, go ahead. Do you have some design in mind for the page?

**Comment by rohitjethoe** [comment]
@maaverik I'll send a screenshot of it if i've made a mockup of it in figma.

**Comment by rohitjethoe** [comment]
Hey @maaverik , I've made a mockup and my question was if it looks good to you. I also think the website needs a footer because it will make the homepage and 404 page look better.

Screenshot(s) of mockup:

<img width="832" alt="mockup" src="https://user-images.githubusercontent.com/69147709/91082148-86186180-e648-11ea-9524-fd561af38097.png">

**Comment by maaverik** [comment]
It looks good Rohit. A few things to note, we're ditching the old design we had, so the color and the button style will be a bit different from this mockup. Take a look at https://new.simplq.me and https://new.simplq.me/123 to see what we have now. We also won't need the blue bar on the top. The design we're following is this: https://xd.adobe.com/view/8d227f50-0d35-4319-63ad-ff4bad308415-fb13/, so the styles should match it. 

You could get started with changing the page, you needn't try to create a mockup, just making the changes and adding a screenshot with the PR is enough.

You can get the right color and most of the CSS constants from https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/styles/utils.scss and a lot of common components like buttons have been implemented with the correct styles in the /common folder. Take a look at the current 404 page code https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/PageNotFound.jsx and you'll see what I mean and you can refer this https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/readme.md to understand the code structure.

Your idea on the footer is good. Do you have a design in mind for it already? We couldn't think of what to add there, so we left it for later.

I've opened a related issue, #195 to vertically center the 404 page. Could you try if you can solve that issue as well? If not, it's absolutely fine, we'll look at it later.

**Comment by maaverik** [comment]
If you need help with anything, just post it here. We'll respond soon.

**Comment by daltonfury42** [comment]
@rohitjethoe Feel free to innovate, what do you think about this?

![image](https://user-images.githubusercontent.com/11256376/91090104-33ec3600-e672-11ea-808e-1153d365d155.png)

Also, you can go to https://undraw.co/search and search for 404, you'll fine nice SVGs... try fitting one of those into your page, (maybe between SimplQ and the subtile)

**Comment by rohitjethoe** [comment]
my opinion: Undraw isn't very professional (anymore). It's to fast and easy. I would suggest making your own illustration or else find less popular ones. The rest looks good.

**Comment by daltonfury42** [comment]
True... My plan is to use undraw for fast prototyping, and replace all illustrations in one go with something less mainstream. In the below one, the whitespacing is messed up... but somewhat close to what I have in mind:

![image](https://user-images.githubusercontent.com/11256376/91090628-00f67200-e673-11ea-8db3-20650382126a.png)

**Comment by maaverik** [comment]
The only thing I dislike about this is the simplq heading. It looks too much like the homepage. If it's at least smaller, it would look better imo.

**Comment by daltonfury42** [comment]
Yes. Maybe smaller (one third current size) and positioned at top right corner? then 404 image can move up and spacing can be increased between the image, the subtitle and the buttons.

**Comment by maaverik** [comment]
That sounds like it'll look good. @rohitjethoe could you think about what variation would look best? If you have other ideas or pictures we could use, let us know.

**Comment by daltonfury42** [comment]
Final Design:

![image](https://user-images.githubusercontent.com/11256376/94367380-f872da80-00fb-11eb-83f3-308c6d0996c6.png)

Design: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/3ce6558d-f906-44f2-8860-3487ee917c98

**Comment by daltonfury42** [comment]
@rohitjethoe are you still interested in taking this up?

**Comment by arc30** [comment]
A minor suggestion - Having 404 explicitly written somewhere in the page would be a good idea @akashkbaburajan

**Comment by arc30** [comment]
A minor suggestion - Having 404 written explicitly somewhere in the page would be a good idea. @akashkbaburajan

**Comment by himankpathak** [comment]
Hey @daltonfury42, I would like to work on this issue. Let me know if it's up for taking.

**Comment by daltonfury42** [comment]
yes sure, this is up for grabs

**Comment by himankpathak** [comment]
Great. @daltonfury42 Just confirming Is this the final design we are trying to build? 
https://github.com/SimplQ/simplQ-frontend/issues/193#issuecomment-699642650

The wave box at the bottom seems to missing style in Adobe XD, Is it supposed to be a asset or built with CSS?
Also, is there also a design for mobile screen view?

**Comment by daltonfury42** [comment]
Yes,  the design is correct. 

The wave box is currently present as a jsx element [here](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Home/LandingPage.jsx#L17), can you move it out to public/images/wave.svg and reuse it here?

**Comment by himankpathak** [comment]
Okay sounds good.
Is there a mobile view design?

**Comment by daltonfury42** [comment]
We don't have one. Can you work using the desktop design, and flex-wrap the left and right half so that the right side svg will move down to the next line on smaller screens?

**Comment by himankpathak** [comment]
Yea sure, I can do that. Please assign me the issue. I will move forward with it.
