### ISSUE TITLE
Can we have a "Star us on github" link somehere?

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#198]
<img width="1585" alt="Screenshot 2020-08-29 at 11 59 58 AM" src="https://user-images.githubusercontent.com/11256376/91634780-a6fa0180-ea10-11ea-8272-b27cba9cdbdd.png">

https://buttons.github.io/

**Comment by akashkbaburajan** [comment]
![Adobe XD 27-09-2020 12_47_00](https://user-images.githubusercontent.com/16539463/94358550-8ed4db00-00bf-11eb-8820-02b950b2934f.png)
I have put this on our new design footer

**Comment by daltonfury42** [comment]
Hmm. Can this be a button instead of a link?
