### ISSUE TITLE
Move queue history to Queue Settings page

### ISSUE THREAD

**Issue by akashkbaburajan** [SimplQ/simplQ-frontend#200]
The queue history need not be in queue admin page but instead in queue settings page - Reason being 
1. You dont want to clutter queue admin page with a lot of information
2. Queue history is not a critical functionality which needs to be on the main page. 
![Queue History in Queue Admin Page](https://user-images.githubusercontent.com/16539463/91635334-62249980-ea15-11ea-90cd-02cc32a9180a.png)

**Comment by daltonfury42** [comment]
hmm. I am of the opinion that the expansion panel, which will be closed by default, should be fine.

**Comment by akashkbaburajan** [comment]
naa... i think having it separately will be cleaner. Updated design - https://xd.adobe.com/view/99a3a298-8f0c-468a-6cf3-614e96f6f9f5-ef92/
![Queue History](https://user-images.githubusercontent.com/16539463/91635937-32c45b80-ea1a-11ea-8ea0-e41cc422c3cc.png)
![Queue Settings](https://user-images.githubusercontent.com/16539463/91635938-33f58880-ea1a-11ea-95c8-119bd57513b8.png)

**Comment by daltonfury42** [comment]
I'm a bit concerned about how things will turn out on desktop... all the above screens look good on mobile screens, but we should not be allocating a page per each of these, and it will look bad on bigger screens.

**Comment by daltonfury42** [comment]
I'm strongly in for keeping the live queue, live history, pause/delete queue button and all directly visible on the admin page. and somehow intelligently designed so that they will arrange themselves well between mobile and desktop...
 
1) There could be things side by side on bigger screen, and then will go down into one item per row on mobile.

2) We should not hide these stuff behind other screens, we should show directly on the main page.

**Comment by daltonfury42** [comment]
Rough idea about what I mean, things should automatically wrap down on small screens. On deskop, we would have two things side by side, and on mobile they will all be on single line.

![image](https://user-images.githubusercontent.com/11256376/91637963-b76aa600-ea29-11ea-96d0-68092fa534d7.png)

**Comment by daltonfury42** [comment]
Think UX... reduce clicks as much as possible... if everything is available on the admin dashboard, no need to click around... Here to see the queue history the user would have to do three clicks... Lets discuss on call

**Comment by daltonfury42** [comment]
![image](https://user-images.githubusercontent.com/11256376/91638449-58a72b80-ea2d-11ea-86d1-eda7bf9d9e8a.png)

I was just studying the github issues page... The main thing about the issue page is the discussion that happens on the middle, and takes 50% of the width, 30% is other controls (assignees, labels etc), and remaining 20% is margin. We should utilise screen real estate.

Now open the same page on mobile, and you'll see things "wrapping" down.

**Comment by daltonfury42** [comment]
Addressed in new design
