### ISSUE TITLE
[Technical]Explore and integrate sentry

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#201]
https://sentry.io/

**Comment by maaverik** [comment]
I'll look into this. It seems interesting.

**Comment by daltonfury42** [comment]
Yes, it might be useful for us. They have a free plan that might suit our
needs too

**Comment by maaverik** [comment]
I can't test this out while running it locally. I'll research a bit more and try pushing the changes soon to see if it actually runs as expected.
