### ISSUE TITLE
Admin Dashboard - Copy and Refresh Button Placement

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#204]
![A1D5750A-3A15-4386-B6D5-8D7330410F49](https://user-images.githubusercontent.com/13188906/91877077-2995f180-ec9b-11ea-873b-a0fbb7451964.jpeg)

Redesigning share link , since we’re technically just copying . Refer bit.ly

**Comment by daltonfury42** [comment]
+1

**Comment by maaverik** [comment]
I prefer not showing the actual link, just a copy button. The refresh button can be next to it too as suggested. So, in effect it would be just changing the text of the share button we have right now to something like 'Click to copy link' which could change to say Link copied for about 5 seconds or so after clicking.

**Comment by sajmalyousef** [comment]
https://blog.prototypr.io/3-ways-to-copy-to-clipboard-5077f5774b55 , there are 3  designs suggested here. And I see a very valid point .
"While adding a button is a good option, it requires the user to learn and follow a new procedure. In addition, there’s not a widely recognized icon for copying to clipboard, which can make it difficult to spot the functionality. "
And lets give the option to the user , if he wants to copy to or use our button to do the same.

**Comment by daltonfury42** [comment]
This was a good idea, but later on, the new button in the latest design was also looking good.

@sajmalyousef What do you think we should do? Can we leave it as is in the new design or you think we need to change?
