### ISSUE TITLE
[HomePage] Landing Section (Without Navbar)

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#208]
![image](https://user-images.githubusercontent.com/11256376/92302173-98b76280-ef87-11ea-8ccb-ab55a561b22b.png)

When homepage is visited, the user should be presented with what is in the image above. Upon scrolling down, other contents in the page will come, but this should be the exact view when the user lands on the page, independent of the screen height. 

1. The curved violet area in the bottom should be there in the view like in the screenshot, no matter what the height of the screen is. 
2. The remaining contents of the homepage should come only on scrolling down.
3. Mobile should also have same experience

https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

Aim: Love at first sight. 😆

**Comment by maaverik** [comment]
The input field and the buttons are unreachable right now due to the placement of the CreateJoinForm. I believe we need to sort out the positioning to fix this.

**Comment by daltonfury42** [comment]
Yeah, I had made only the react component level changes. We need to make
the CSS changes.

I just tried on mobile, and it's totally screwed up. 😅

**Comment by daltonfury42** [comment]
Done
