### ISSUE TITLE
[HomePage] Create Queue and Join Queue "How To" Section Redesign

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#210]
In the current homepage, on scrolling down, there is a slider titled "Create a Queue at the click of a Button":
![image](https://user-images.githubusercontent.com/11256376/92309569-53655600-efc4-11ea-89ca-96718cf70684.png)

The slider can be removed, and then replaced with three cards like this: 

![image](https://user-images.githubusercontent.com/11256376/92309578-6d069d80-efc4-11ea-9474-26991d5589e2.png)

On wider screens the three cards will be on a single row, but on screen width getting smaller, the cards should flex-wrap down to the next line:
```
flex-wrap: wrap;
justify-content: center;
```

Same for the Join Queue Section:

![image](https://user-images.githubusercontent.com/11256376/92309734-bdcac600-efc5-11ea-8521-60103573572a.png)

Design Link: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

**Comment by daltonfury42** [comment]
Should these cards lift up on hover as is suggested in https://github.com/SimplQ/simplQ-frontend/issues/188 ?

**Comment by daltonfury42** [comment]
Proposal: We should replace with cards as above only bigger screens. On mobile, the slider might be better. 

Rationale: Otherwise, on mobile it would be 8 cards coming on 8 line. It will be long and repetitive scroll. 

We could explore [react-responsive](https://www.npmjs.com/package/react-responsive) for achieving this.

https://medium.com/@kkomaz/react-responsive-its-pretty-cool-d61e5ed56d95

**Comment by daltonfury42** [comment]
Hmm... I want to reduce the number of cards we have on our page. We have 3 rows of cards, total 8 of them.

Can we reduce them... I think we have too much.. Rather than 8 cards, we should just show 4-5 "to the point" ones... We don't have 8 points to convey.

cc: @sajmalyousef @akashkbaburajan @maaverik

**Comment by daltonfury42** [comment]
We can have one row of cards, remaining, we should have maybe a non card svg and two lines of text side by side

**Comment by daltonfury42** [comment]
Another layout idea
![Uploading Screenshot 2020-09-21 at 5.35.12 PM.png…]()

**Comment by akashkbaburajan** [comment]
Yea that's a very valid point. There are just too many cards in the new home page. I'll update the design with the suggestions you have provided

**Comment by akashkbaburajan** [comment]
Updated the "Why SinplQ" ang "How To" sections of home page.
removed boxes of the tiles in "Why SimplQ" section
![Adobe XD 26-09-2020 19_59_07](https://user-images.githubusercontent.com/16539463/94358626-0c005000-00c0-11eb-9ea0-bb61707d9a0c.png)

revamped the "How To" section to not have tiles.
![Adobe XD 26-09-2020 19_58_49](https://user-images.githubusercontent.com/16539463/94358640-1d495c80-00c0-11eb-8ad2-d4d858851a9e.png)
![Adobe XD 26-09-2020 19_58_59](https://user-images.githubusercontent.com/16539463/94358642-1fabb680-00c0-11eb-8c95-aa5376199310.png)

**Comment by KasiKral** [comment]
Hi, can I work on this? To be clear, this issue of the redesign is meant to be implemented or only make suggestions to design. If you need to implement this i would like to.

**Comment by daltonfury42** [comment]
Hi @KasiKral we need to implement this designYes you can. We need to implement this design: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

**Comment by maaverik** [comment]
https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/grid/ The above link doesn't work for me. If anyone else has the same problem, try this.

**Comment by maaverik** [comment]
Never mind, looks like a problem with firefox. I guess we have to use chrome for now.

**Comment by KasiKral** [comment]
Okay, I'll make changes according to "Web: Home – 2"([https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/](url)) design.
