### ISSUE TITLE
[HomePage] Features Section Redesign

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#211]
Our features Section looks like this currently: 

![image](https://user-images.githubusercontent.com/11256376/92309776-01bdcb00-efc6-11ea-9e11-a8acf5a91a55.png)

Transform it into: 

![image](https://user-images.githubusercontent.com/11256376/92309789-15693180-efc6-11ea-9356-d7c163ca8f14.png)

Design: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

**Comment by arkumari2000** [comment]
Hello,
I will be happy to do this.
please assign me this issue.

Thank you

**Comment by maaverik** [comment]
Hi @arkumari2000, this item has already been taken care of. Take a look at https://new.simplq.me. The latest code is running here. So closing this item.
