### ISSUE TITLE
Curved Divs For New Homepage

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#213]
As per the new design, there are two curved divs on the homepage. Should be doable with some SVGs.

https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

A tutorial which might help: https://redstapler.co/curved-custom-shape-div-css-svg/

**Comment by daltonfury42** [comment]
Raised PR #216 for the landing page div

**Comment by maaverik** [comment]
This is completed, right?

**Comment by daltonfury42** [comment]
According to our current design, there is one more curved div. But @akashkbaburajan would revisit this section, so let's keep this task on hold.
