### ISSUE TITLE
[HomePage] Implement Homepage Navbar

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#214]
Design: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/

![image](https://user-images.githubusercontent.com/11256376/92310735-c83d8d80-efce-11ea-9fe3-92643e13571c.png)

1. This navbar is specific to the home page. 
2. My Queues and SignIn/SignUp need not be implemented right now
3. The navbar should be responsive. On mobile it should become a hamburger menu. (Like the bootstrap navbar)

**Comment by arkumari2000** [comment]
Hello,
I want to give it a try.
please help me how can I move forward?

Thank you

**Comment by maaverik** [comment]
Hi @arkumari2000. This item involves creating a new component for the navbar which would go inside simplQ-frontend/simplq/src/components/pages/Home/. The related styling to use should go in  simplQ-frontend/simplq/src/styles/homePage.module.scss as new appropriately named classes. To begin with, please go through these files and this [readme](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/readme.md). Once you're done with that, think about how you would want to approach this and we can discuss that here and finalize.

**Comment by maaverik** [comment]
Just to add, if you're new to web dev or react, start by googling 'How to build a responsive navbar in react', see how much you can understand from the first few links, and we can go from there.

**Comment by daltonfury42** [comment]
Let's break this task into two PRs.

Start with a very simple non-responsive navbar. Just a white div with the Icon, Home, How It Works and Contact Us link would do.

You can then work on responsiveness in a follow up PR or work on another task.

**Comment by arkumari2000** [comment]
> Just to add, if you're new to web dev or react, start by googling 'How to build a responsive navbar in react', see how much you can understand from the first few links, and we can go from there.

Thank you. I will try this and if something will come up I will inform.

**Comment by arkumari2000** [comment]
> Hi Archana, welcome.
> 
> Let's break this task into two PRs.
> 
> Start with a very simple non-responsive navbar. Just a white div with the Icon, Home, How It Works and Contact Us link would do.
> 
> You can then work on responsiveness in a follow up PR or work on another task.

Thank you for assigning me and breaking PR into two tasks. 
I am trying and if I will get success I will inform you.

**Comment by arkumari2000** [comment]
Hello,
I am trying to run this project and it is showing this error. I have searched a lot and removed and reinstalled npm but still it's not working. 
Can you help me with this?
![Screenshot from 2020-09-23 12-55-55](https://user-images.githubusercontent.com/48750169/93980492-528e3b80-fd9c-11ea-8aa2-42acee99e103.png)

**Comment by daltonfury42** [comment]
Run this to see if the error went away:
```
$ sudo sysctl fs.inotify.max_user_watches=524288
$ sudo sysctl -p
```

If it did, you can make it permanent:
```
$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -p
```

This is because CRA/React watches a lot of files, and this exceeds the max file watch limit in linux. https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

**Comment by arkumari2000** [comment]
@daltonfury42  Thank you, it worked.
