### ISSUE TITLE
[Technical]Research if we should migrate to partial server side rendering

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#222]
We have a client-side rendered app right now and from what I understand, SEO and social media sharing doesn't work very well with client-side rendered JS apps yet. It might be a good idea to at least partially move our app to an SSR model. We could maybe have just our homepage pre-built and sent from the server. This would speed up load times and help with SEO. More research is needed on if this is a good choice, if it's worth the effort and on the best tools to do it if we are going this route like Next.js or Gatsby. 

This is a good reference: https://blog.logrocket.com/why-you-should-render-react-on-the-server-side-a50507163b79/

**Comment by daltonfury42** [comment]
Yes this is a really good idea, we should serve our homepage as a static site. How about we complete development of homepage in this repo and simple move it into the backend? Backend can serve it as a static html file.

I don't think we should rewrite our entire backend for this, though. Gain to effort ratio is very low. We would have to one of these frameworks, and also, it's not as mainstream/popular as react/java is, I believe. For example, we might get collaborators easily for a React+Java stack.

**Comment by maaverik** [comment]
There's no need to rewrite the backend. If we are using a framework like next, it would run as a separate service from our java backend, only handling serving the frontend (essentially replacing node in the browser) as far as I understand. But it might be overkill for us since our homepage just has two buttons and no other dynamic stuff. We could just rewrite it with pure HTML once we're done and set it up as the public html index page.

**Comment by daltonfury42** [comment]
Now I'm wondering if we should wait till we make the home page and then migrate to html... I think it's better that we do it now itself...

I think once it's a static HTML file, we can also leverage bootstrap for two reasons (not fully convinced, we should think more):

1) Responsiveness
2) They have a good navbar, that is responsive and would reduce to hamburger (sidebar) on mobile.

What do you think?

**Comment by maaverik** [comment]
I'm with you on that. Moving it now makes more sense. We could just continue to make the changes after making the page static. It's all css changes anyway. I'm not sure it'll be quite that easy to just replace the public html file we have right now with a static one and still have all our react code work fine though. We'll need to figure out how to best do that. 

The browser has to load this static file and the bundle at the same time. Also, if a user starts out on a different page like the join or admin page, then the homepage shouldn't come up at all, so it isn't going to be as simple as replacing the public html file.

**Comment by daltonfury42** [comment]
It's theoretically possible. Let try check this weekend.

**Comment by daltonfury42** [comment]
On quick look, Gastby looks very interesting. @maaverik can you do some experiments on it for simplq, in a new branch? We could try it out, and then decide if we should use it.

**Comment by maaverik** [comment]
Okay

**Comment by daltonfury42** [comment]
A concern from my side is, we should not mix multiple technologies together unless there is a strong need to do so.

For example, if I am building a big application, I don't want some parts to be on react, some on angular and some on a totally different technology. Even if it's technically possible to do that, we shouldn't unless there is a strong reason to mix them.

Another example is, if you are building a complex application backend, you should not use separate languages for different microservices, even though microservices work fine that way. For example, user service is written in golang, booking service is written in java while xyz was written in nodejs -> might be a bad idea, as the cost of managing all these variety of tech stacks is very high.

Long story, but the point is, if we are going to move to Gastby, we might be better off completely migrating the entire site to use it... so think from that point to... We should not have home page in Gastby, and admin page using vanilla React.

But my comments are not after a full/proper understanding of Gastby, so before you spent effort on this, keep this also in mind. From a cost perspective.

**Comment by daltonfury42** [comment]
https://youtu.be/j6ow-UemzBc?t=221 See a minute on this point, this is one reason I don't feel excited to introduce a new framework.

**Comment by maaverik** [comment]
This is not required anymore, so closing. If we ever want to explore this again, we can look at #227 or one of the other options mentioned above.
