### ISSUE TITLE
[Queue Admin dashboard] Modify existing share link button as per the new design 

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#223]
#207 Refer this issue for the detailed roadmap

Position the "Copy queue link"  button adjacent to Queue name as per the [design](https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8)

1. User clicks on the below button to copy the queue link
![image](https://user-images.githubusercontent.com/13188906/92788768-da9d3a00-f3c7-11ea-9a24-6102394ea39c.png)

2. On clicking, the link gets copied to clipboard and the button appears as   

![image](https://user-images.githubusercontent.com/13188906/92788253-69f61d80-f3c7-11ea-8f2d-2147677b779a.png)

**Comment by mritunjaysaha** [comment]
Hey, I would like to contribute. I was not able to find the exact icon in material-UI. I found one on material design but it only showed a empty img icon. Even the home page icon is not shown in the queue page.
![simplQ](https://user-images.githubusercontent.com/59063979/94727069-cb345f80-037b-11eb-8cc2-cba64d88919c.gif)

**Comment by maaverik** [comment]
Hi @mritunjaysaha, you need not worry about the nav bar and the queue logo not showing up right now. That's being worked on separately. 

As for the icon, can you try downloading the asset directly from here https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/specs/ and trying to add it. You'll find it in the view specs panel on the right.

![Screenshot from 2020-10-01 00-44-16](https://user-images.githubusercontent.com/12583528/94729485-5c590580-037f-11eb-85fd-9a7536c230cb.png)

It looks like the link given in our readme for the current design is outdated. I'll fix that soon.
