### ISSUE TITLE
Admin Dashboard - Skeleton

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#242]
Our current admin page layout looks like this:

![image](https://user-images.githubusercontent.com/11256376/93713149-ab30bf00-fb77-11ea-9a70-195565905d2a.png)

We need to change to

![image](https://user-images.githubusercontent.com/11256376/93713108-8dfbf080-fb77-11ea-9228-b34654962a53.png)

We need to rewrite the component hierarchy, a proposed hierarchy is:

```
<Navbar />

<Header>
QueueName, Description, Share and Update Buttons
</Header>

<TokenList />    <Sidebar />
```

**Comment by daltonfury42** [comment]
@maaverik I think we are better off creating our own simple navbar, and header inside the `admin/` folder, than reuse from `component/`.

What do you suggest?

**Comment by maaverik** [comment]
The header is unique to this page, so I agree. But the Navbar can be reused, right?

**Comment by daltonfury42** [comment]
@akashkbaburajan was planning a different navbar... Not sure if we gain a lot by reusing them... I think you can take the call when implementing

**Comment by daltonfury42** [comment]
In case of admin page, the navbar is mostly just a whilte div, with SimplQ at left, and Sign In at right

**Comment by maaverik** [comment]
Okay

**Comment by daltonfury42** [comment]
@maaverik let's close this?

**Comment by maaverik** [comment]
Yeah, it's fine to close. The skeleton is done. Only the add user form is left other than the token change. We can open another issue for that.
