### ISSUE TITLE
[Admin Dashboard] Header Section Styling

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#251]
Header section on the QueueAdmin page should look like below.

![image](https://user-images.githubusercontent.com/11256376/94363282-c010d380-00de-11eb-8468-606985cfea72.png)

1) The nav-bar is just a simple white div with the SimplQ+icon on the right side. Clicking on the icon should take the user to the home page. 
2) Ignore `Sign Up/Sign` and the queue description below the title, it can be added later.
3) The "Copy Queue Link" button can be styled separately in a different PR (see https://github.com/SimplQ/simplQ-frontend/issues/223)
4) The section should look well on mobile screens. Things should flex-wrap sensibly.

**Comment by lukigarazus** [comment]
I can handle this one

**Comment by daltonfury42** [comment]
This is blocked on https://github.com/SimplQ/simplQ-frontend/issues/214 

We will refactor #214 to handle admin page once that is done.

**Comment by daltonfury42** [comment]
Hi @lukigarazus Would you like to take this up? I've edited the description to make the task more clear.

Also it might be a good idea to take up https://github.com/SimplQ/simplQ-frontend/issues/223 before coming to this.

**Comment by mritunjaysaha** [comment]
Hi @daltonfury42 , I would like to take this up.

**Comment by Gh05d** [comment]
I have submitted a PR for this.
