### ISSUE TITLE
[Design] Redesign fork on github ribbon

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#252]
Incorporate a contribute on github button. 

![image](https://user-images.githubusercontent.com/13188906/93999398-62fde080-fdb3-11ea-89f1-7ae25fb012c4.png)

Refer this for a better idea. 
https://www.coronawarn.app/en/

I was thinking of keeping it in the navbar

**Comment by Gh05d** [comment]
I submitted a PR for this.
