### ISSUE TITLE
[AdminDashboard] Tokens

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#264]
The admin Page Tokens has to be updated to the new design. 

Currently each token looks like this:

![image](https://user-images.githubusercontent.com/11256376/94363851-b6896a80-00e2-11eb-9e55-5a82b0a1d87b.png)

It should look like this:

![image](https://user-images.githubusercontent.com/11256376/94363606-f3ecf880-00e0-11eb-8515-08de467e5200.png)

Note: During Development, to create tokens in the queue, take the queue joining link and got to a different browser tab to add people to the queue.
Note 2: On clicking Remove, a confirmation is asked from the user, which we can ignore for now

**Comment by mritunjaysaha** [comment]
hi @daltonfury42 , Can I take this up?

**Comment by daltonfury42** [comment]
Sure, this is a nice task

**Comment by mritunjaysaha** [comment]
Working on it. I could not find the call logo in resources

**Comment by maaverik** [comment]
@daltonfury42 do you have the link to the Adobe XD design for this token. I can't find it. It should have the asset.

**Comment by daltonfury42** [comment]
Right. I checked with, we need to ask @akashkbaburajan to "export the particular asset". Not all assets might have been exported. 

@akashkbaburajan can you check?

**Comment by akashkbaburajan** [comment]
I have updated the design link but you can always get them from https://material.io/resources/icons/?style=baseline This is where I got the commonly used icons
