### ISSUE TITLE
[Navbar] Clicking outside the sidebar on mobile should close it

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#276]
When in mobile / smaller screens, the navbar switches to an expandable drawer. When the drawer is expanded clicking anywhere outside the drawer should automatically collapse it:

<img width="635" alt="Screenshot 2020-10-02 at 2 26 31 AM" src="https://user-images.githubusercontent.com/11256376/94862746-06f02780-0457-11eb-8aaa-908584fc0b1a.png">

**Comment by Kannndev** [comment]
Can I pick this up? I am thinking of putting an overlay left to the drawer and Clicking on it would close the drawer

**Comment by daltonfury42** [comment]
Yes, you can. 

Maybe you can add a dark tint to the overlay: https://medium.com/allenhwkim/close-div-when-clicking-outside-it-97255c20a221

**Comment by Kannndev** [comment]
Cool. Thanks can you asiign this to me Please

**Comment by Kannndev** [comment]
Raised PR. Please review. #283
