### ISSUE TITLE
Add footer on home page to all pages

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#278]
Our footer is present in the home page [here](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Home/StaticInfos.jsx#L117) as part of StaticInfos.

We should to move it to [simplq/src/components/common](https://github.com/SimplQ/simplQ-frontend/tree/new-frontend/simplq/src/components/common) and add it to the [Layout](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/Layout.jsx) to make it common to all pages.

The associated css can be moved into [styles folder](https://github.com/SimplQ/simplQ-frontend/tree/new-frontend/simplq/src/styles) by creating a new file `layout.module.css`

![image](https://user-images.githubusercontent.com/11256376/94900493-b5758600-04b2-11eb-88fb-b59c1c9f7038.png)

**Comment by deprov447** [comment]
@daltonfury42 May I work on this?

**Comment by daltonfury42** [comment]
Please do. This is up for grabs

**Comment by daltonfury42** [comment]
Can you also add suitable top and bottom padding while you are at it?

**Comment by deprov447** [comment]
Ohkay I will.

**Comment by daltonfury42** [comment]
Thanks for fixing this, @deprov447
