### ISSUE TITLE
Restyling Status Page

### ISSUE THREAD

**Issue by deprov447** [SimplQ/simplQ-frontend#281]
> This is with reference to Issue #180 

Above mentioned issue specifies restyling the  _Notification button on Queue Status page_. 
Thus It seems like there is a parent issue to restyle other components on this route too. It is requested to discuss the new styling of the page and contribute appropriately.

**Comment by daltonfury42** [comment]
Right, I have made a proposal here. https://github.com/SimplQ/simplQ-frontend/issues/282

What do you think? Let me know if you are interested in taking this up.

**Comment by deprov447** [comment]
Thanks @daltonfury42. But currently I am unable to take up the whole task, but definitely can help with some part of it :)

**Comment by maaverik** [comment]
Closing as notification button has been replaced by a toggle.
