### ISSUE TITLE
Logo and Text on Navbar Should Remain Constant on Transition Between Admin and Home Pages

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#287]
![ezgif-6-b9faee592e07](https://user-images.githubusercontent.com/11256376/94934377-45cebd80-04e9-11eb-9e56-3b4527a3928e.gif)

When the user moves between home and admin pages, the transition should not shift the the logo and the "SimplQ". Proposed change:

1) On home page navbar, replace "Home" with "SimplQ" as is present on Admin Page:
![image](https://user-images.githubusercontent.com/11256376/94934080-e1136300-04e8-11eb-9329-4d67185ec290.png)

2) Font size and positioning should be made same between both the pages. End goal is to make the navbar not change in size across the page transition.

@akashkbaburajan What do you think?

**Comment by arkumari2000** [comment]
I want to give it a try. Please assign it to me.

**Comment by maaverik** [comment]
Sure, go ahead

**Comment by arkumari2000** [comment]
Do you want it like this?

![check](https://user-images.githubusercontent.com/48750169/94988579-f5f50280-058b-11eb-9453-238e3f8fb1b5.gif)

**Comment by maaverik** [comment]
This looks good. It would look the same on mobile view too, right?

**Comment by arkumari2000** [comment]
Yes.

**Comment by maaverik** [comment]
Merged. Great job.

**Comment by arkumari2000** [comment]
@maaverik Thank you
