### ISSUE TITLE
Implement Add Manually Section in Admin Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#289]
Implement the [Add Manually Section](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Admin/AddMember.jsx) in admin page:

![image](https://user-images.githubusercontent.com/11256376/94943897-0e1a4280-04f6-11eb-9a7b-e9f944011ea2.png)

It will expand on click to a form to add a person to the queue taking name and phone number. We should reuse the [Form](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Join/Form.jsx) component, if possible.

Pass this `joinQueueHandler` to `Form` which will make the API call and then update local state of the admin page:

https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Admin/AdminSidePanel.jsx#L10

Design Link: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8

**Comment by mritunjaysaha** [comment]
hi @daltonfury42 , I would like to take this up. I can think we need to complete this before one can start with #284 ?

**Comment by daltonfury42** [comment]
This is a pretty good change to work on. The Form component need to be reused in two different pages. We will use it here in the add manually section, and also in the join queue page (which comes if you copy the joining link to clipboard and paste it in a different tab).

So #284 can be taken up independently by accessing the form from the Join Queue page.

Feel free to take this up.

**Comment by mritunjaysaha** [comment]
Working on it.

**Comment by thehamzarocks** [comment]
Just a comment on the UI, maybe we can make the label simply "Add Member" instead of "Add Member Manually" since the description makes it clear. And the long label text appears in two lines on some phone displays.

**Comment by daltonfury42** [comment]
Yes, let's do that.

**Comment by iam-Akshat** [comment]
Isnt this issue closed?

**Comment by maaverik** [comment]
Well, not completely. The addition of the collapse component has broken the styling and caused the sidebar to appear centered. This has to be fixed. The collapsible part had to appear below the text not beside it.
