### ISSUE TITLE
Implement the side panel functionality and notifications toggle for the status page

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#291]
The design is given here: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e87838cd-febc-4f37-a68a-9daa0d6b207b

![image](https://user-images.githubusercontent.com/11256376/94956660-2f852980-050a-11eb-8093-f563432b5fcf.png)

The task is to let the user leave the queue on clicking Leave Queue (the confirmation dialog can be implemented later) and expand the Queue Details card to see correct queue information. The above link points to an interactive page that shows how the complete version would look like. 

The setup for the API calls for these two are already done. Start by looking at src/components/pages/Status/QueueStatus.jsx. There is some commented code in src/components/pages/Status/QueueDetails.jsx which can probably be reused to get the right format we need. The icons used are available from materialUI.

The notifications toggle should replace the notification button that we had previously. This logic can be found in src/components/common/NotificationButton.jsx and the corresponding ask function has to be called on toggling it on and ideally, all cases must be handled elegantly. 

Any questions can be discussed here. You can start by working on a single item discussed above, e.g., just the Leave Queue part or just the toggle, and  work on the rest in separate PRs.

**Comment by Gh05d** [comment]
Hey, I submitted a pull Request for this ticket. The modal confirmation dialog is not yet implemented, the user gets simply pushed back to the root route when he clicks on the button.

Also, I did not implement the full card view, because I could not find in the xd sheet how it shall look.

Which cases should be handled in the Notification logic? I just ported the logic of the button to a switch (which currently has the default styling).

I would continue working on these issues if the pull request was ok and maybe some more context was given.

**Comment by maaverik** [comment]
Hi @Gh05d, thanks for the PR. I've added some comments there. Please take a look.

The dialog can be implemented later, so no worries. I don't understand what you mean by the full card view. Could you elaborate a bit?

**Comment by Gh05d** [comment]
When you click on Queue Details, my understanding is that that row should expend and the user should get more information about the Queue.
 
Will take a look at the pull request. By the way, is there any chance to add the _hacktoberfest_ topic to the repo? ;-)

**Comment by daltonfury42** [comment]
We have added the topic, so once your PRs get merged it should get counted. 

Let's split this task into multiple PRs, we can deal with the queue details changes in subsequent PRs.

**Comment by Gh05d** [comment]
Thanks.

I resolved most of the comments, but some questions remain. Please check.

**Comment by maaverik** [comment]
Thank you @Gh05d for the work so far at #332. Now what remains are the queue status part and styling tomatch the admin page.

**Comment by maaverik** [comment]
We'll open separate issues for those after maybe refactoring the code a bit, but you're free to start working on it if you want @Gh05d.
