### ISSUE TITLE
Implement the token number and position sections in the status page

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#292]
The design is given here: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e87838cd-febc-4f37-a68a-9daa0d6b207b

![Screenshot from 2020-10-03 00-04-43](https://user-images.githubusercontent.com/12583528/94957823-17aea500-050c-11eb-982b-901fcbd98af8.png)

The task is to implement the parts on the left of the status page, the token number and the central part with the position in the queue to look like the design above. The setup for the API calls for these two are already done. Start by looking at src/components/pages/Status/QueueStatus.jsx. 

After taking a look, let us know if you feel like there are any places you might get stuck at, and we can discuss those here. You can start by working on a single item discussed above, e.g., just the token number part, and work on the rest in separate PRs.

**Comment by deprov447** [comment]
I am working on this @maaverik

**Comment by maaverik** [comment]
Sure

**Comment by daltonfury42** [comment]
Hi @arkumari2000 Implementing that token number would be an interesting task, would you like to pick it up? 

![image](https://user-images.githubusercontent.com/11256376/95022274-d34e1100-0693-11eb-87e1-e771f3a2757a.png)

@deprov447 let us know if you are working on this

**Comment by deprov447** [comment]
Sorry, I'm overloaded these days. Would be helpful if someone can takeover. or else give me a week :/

**Comment by iampankajgupta** [comment]
can i work on this issue

**Comment by daltonfury42** [comment]
sure, go ahead

**Comment by sofistoyanova** [comment]
is anyone working on it?

**Comment by maaverik** [comment]
You can start on this if you want @sofistoyanova. If there aren't any open PRs and there hasn't been any progress on an issue for a while, feel free to work on it. Is anyone else working on this right now @iampankajgupta @deprov447 ?

**Comment by maaverik** [comment]
The main position container is done now. As for the token number, I personally feel like it looks better with just the text and no background color. So closing this issue for now. Will reopen a new one if required.
![Screenshot from 2020-10-26 13-56-07](https://user-images.githubusercontent.com/12583528/97149654-10895880-1793-11eb-888e-22ed0b1e3d1e.png)
