### ISSUE TITLE
Status page: Logo should redirect to the home page

### ISSUE THREAD

**Issue by Vishv07** [SimplQ/simplQ-frontend#296]
![logotohomepage](https://user-images.githubusercontent.com/37216460/94991204-22fee080-059f-11eb-864b-d5f8578db3d2.JPG)

There's no action after clicking on logo , logo should redirect to the homepage

**Comment by maaverik** [comment]
Hey @Vishv07, this status page is undergoing a redesign and this issue will be taken care of during this redesign. Take a look at #282 to understand more. I'll modify this issue to add this redirection in the new design in a little while. If you want, you can try working on it.

**Comment by maaverik** [comment]
The header on the status page should have the logo and simplq on it as shown in the image below. These should redirect to the homepage on click.

![Screenshot from 2020-10-03 19-18-42](https://user-images.githubusercontent.com/12583528/94993288-84c64700-05ad-11eb-90cb-25891d8e8a93.png)

This logo has already been used in the admin and home page navbars and so could either be converted into a component of it's own and used here or if that's a little too difficult, you can make a copy of the code for now and we can refactor later.

**Comment by Vishv07** [comment]
@maaverik So are you trying to say we should put this whole header on the status page.

**Comment by maaverik** [comment]
The header is already there. The logo and image on the left aren't.

**Comment by Vishv07** [comment]
Okk I'll make it done , will open PR soon

**Comment by maaverik** [comment]
I've opened #328 to make the logo reusable. Maybe hold off till that's merged. Then you can reuse it here and make required styling changes.

**Comment by Vishv07** [comment]
Cool , Will do that

**Comment by iampankajgupta** [comment]
can i work on this issue

**Comment by Vishv07** [comment]
@iampankajgupta i am already working on It , Probably will open PR today 👍

**Comment by maaverik** [comment]
Thanks for the PR @Vishv07. Great job.
