### ISSUE TITLE
Hamburger Menu Missing on Admin Page

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-frontend#299]
Currently, on mobile displays, the hamburger menu is missing from the admin page. It would be convenient to have it across all pages.

**Comment by daltonfury42** [comment]
In admin page we were not planning to have our full fledged navabr (which could make the users navigate away), till we implement my queue and auth

**Comment by thehamzarocks** [comment]
Hmm yes, once they navigate away, they cannot easily come back to the queue page, so let's leave it out until my queue functionality has been implemented.

But users can still accidentally navigate away by clicking on the logo.

**Comment by daltonfury42** [comment]
Yeah, right. We can move the navbar out of home page into a common section and reuse it in admin and other pages, once we implement my queue. We are blocked on authentication

**Comment by daltonfury42** [comment]
I want to do a simple googe auth, like what you did for brainylog... I don't want to go the cognito route.
