### ISSUE TITLE
Copy button expanding on clicking

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#303]
The copy to clipboard is increasing in height when clicked. This is happening due to the height of the new icon on changing.

We need to fix the height of both the icon to be same as other icons

![copy](https://user-images.githubusercontent.com/11256376/95001046-fb7e3700-05e3-11eb-9fa1-8e9197c55169.gif)

**Comment by nikldev0** [comment]
Hi, could I have a go at fixing this?

**Comment by daltonfury42** [comment]
Sure, you are welcome

**Comment by daltonfury42** [comment]
@nikldev0 has fixed the hight, but still the button is expanding in width:

![ezgif-7-96b5bce3618c](https://user-images.githubusercontent.com/11256376/95117643-88e99480-0766-11eb-9824-b69ccdabea34.gif)

If possible, can we add a fixed with to just this button?

**Comment by sofistoyanova** [comment]
can i take it?

**Comment by maaverik** [comment]
Sure. Go ahead.

**Comment by mubashiralisiddiqui** [comment]
Pull request created for this issue please review it
https://github.com/SimplQ/simplQ-frontend/pull/375
