### ISSUE TITLE
Add Member Expansion Panel Smoothness

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#304]
We have an expansion panel for adding members. Make the open/close transition smooth

![transition](https://user-images.githubusercontent.com/11256376/95001110-94ad4d80-05e4-11eb-98b5-b5733d3c6148.gif)

**Comment by peakercope** [comment]
hey @daltonfury42 
I can help with this if you want

**Comment by daltonfury42** [comment]
Hi @peakercope Please do. Thanks!

**Comment by daltonfury42** [comment]
@peakercope Thanks for fixing this

**Comment by peakercope** [comment]
you're welcome!
let me know if there is anything else where I can help
