### ISSUE TITLE
Adding User Manually Doesn't Set Token Number

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#305]
When a user is added manually, the token number is not set. This is mostly a js side issue where we are losing the token number

![tokenno](https://user-images.githubusercontent.com/11256376/95001189-451b5180-05e5-11eb-9e3d-0ad78e5cd9e6.gif)

**Comment by karthiksista** [comment]
I am taking this issue :)

**Comment by karthiksista** [comment]
Created a [PR](https://github.com/SimplQ/simplQ-frontend/pull/318) for this issue
