### ISSUE TITLE
Navbar to sidebar transition issue on mobile

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#306]
The transition of the homepage navbar to a burger icon has some styling issues.

![Peek 2020-10-04 02-00](https://user-images.githubusercontent.com/12583528/95001235-ab07d900-05e5-11eb-8d95-73996b2b6f50.gif)

The navbar should disappear and only the burger icon should show up without the sidebar popping up like this. Setting an appropriate min-width should be enought to fix this.

**Comment by daltonfury42** [comment]
He he... A real user's screen won't shrink in width like that I hope... but his is an issue if someone resizes the window.

**Comment by mraguso2** [comment]
Hi! I'm going to give this one try! :)

**Comment by mraguso2** [comment]
Ready for review! pr: #311

**Comment by maaverik** [comment]
Thanks @mraguso2
