### ISSUE TITLE
SimplQ logo and name do not match

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#313]
Currently the icon and the name are two separate clickable entities. There is an unclickable gap in between which is not so great 
![image](https://user-images.githubusercontent.com/13188906/95008733-18ddf000-063a-11eb-908a-cb3bd07ae5eb.png)

These can be made into 1  image  Also the colour of the font can be similar.

**Comment by mritunjaysaha** [comment]
I would like to take this

**Comment by maaverik** [comment]
Good job Mritunjay. This is merged.
