### ISSUE TITLE
[Admin Dashboard] Realign queue name to the center

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#314]
Currently the queue name is aligned to the left.
This could be  centred
![image](https://user-images.githubusercontent.com/13188906/95008933-82aac980-063b-11eb-9e25-6ff0ef3ddc1b.png)

**Comment by daltonfury42** [comment]
This is to be left aligned as per our design.

**Comment by maaverik** [comment]
> This is to be left aligned as per our design.

Yeah, I like this more than centering.
