### ISSUE TITLE
Replacing social media handle names to their corresponding icons

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#315]
Replace these social media / github names to their corresponding icons as seen in standard websites
These are currently vertically aligned and can be changed to horizontal
![image](https://user-images.githubusercontent.com/13188906/95009090-cbaf4d80-063c-11eb-911d-210c2f88c69e.png)

Example:
![how-to-add-social-media-icons1](https://user-images.githubusercontent.com/13188906/95009175-97885c80-063d-11eb-92b0-5163efe40c48.png)

**Comment by Vishv07** [comment]
I think we should redesign the whole footer as well

**Comment by daltonfury42** [comment]
Hi @Vishv07 If you have good ideas, can you send a figma or a screenshot of what you have in mind?

**Comment by daltonfury42** [comment]
I'd rather prefer keeping both than replace the text with icons. If we choose to go icons only, then the contact us form link should be handled somehow.

**Comment by maaverik** [comment]
> I'd rather prefer keeping both than replace the text with icons. If we choose to go icons only, then the contact us form link should be handled somehow.

I agree

**Comment by Vishv07** [comment]
Yes , I have few Screenshots , we can decide which one will be better
1)
![Footer](https://user-images.githubusercontent.com/37216460/95012349-7fbcd280-0655-11eb-8bd4-a9167ba7dcaa.JPG)
2)
![Footer1](https://user-images.githubusercontent.com/37216460/95012353-851a1d00-0655-11eb-8e70-d2682a07665b.JPG)

3)
![Footer2](https://user-images.githubusercontent.com/37216460/95012356-89463a80-0655-11eb-8156-19ba91f5189a.JPG)
4)
![Footer3](https://user-images.githubusercontent.com/37216460/95012361-8cd9c180-0655-11eb-8b7f-6d18db3066c8.JPG)

**Comment by daltonfury42** [comment]
I wonder how they will look when we put our content and colour theme. I'd want you to do a design mockup on figma or xd  before you start implementing.

**Comment by Vishv07** [comment]
Okkk cool , will do that

**Comment by Vishv07** [comment]
Hey @daltonfury42, So I have made one mockup, kindly check

https://www.figma.com/file/mUbKhO71H6F6bsm3se15CC/Untitled?node-id=0%3A1

**Comment by daltonfury42** [comment]
I like this. Let me ask Akash.

**Comment by akashkbaburajan** [comment]
This looks real nice 👍👍

**Comment by Vishv07** [comment]
@daltonfury42 than let me know,  so I'll Open a PR Tomorrow

**Comment by daltonfury42** [comment]
Sure, please do.

**Comment by Vishv07** [comment]
#388
