### ISSUE TITLE
[Admin Dashboard] Button text for refresh and copy to clipboard on mobile

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#316]
The text inside the button should not go to the second line with change in screen size. It should be similar to the desktop version
here https://simplq.me/queue/1c6988bc-ffa0-4a30-9232-9468715ef513
Button can be  made mobile friendly
![image](https://user-images.githubusercontent.com/13188906/95009254-285f3800-063e-11eb-97ee-3421768c3b24.png)

**Comment by daltonfury42** [comment]
I think we can't avoid that... either let it go to the second line or think of better text.

**Comment by daltonfury42** [comment]
Actually bigger buttons on smaller screens are better for touch. So let's reclassify this as feature and not a bug. 👹
