### ISSUE TITLE
[AdminPage] SidePanel should be horizontally centred on Mobile

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#319]
On mobile / smaller screens, the side panel should be centred, it's currently to the left edge of the screen

![image](https://user-images.githubusercontent.com/11256376/95009857-b0dfd780-0642-11eb-8ec3-bcc8df908c2f.png)

To reach this page, create a new queue, and switch to mobile view, then scroll down.

**Comment by abhishekjain35** [comment]
I would like to work on this issue @daltonfury42. If you could assign it to me.

**Comment by daltonfury42** [comment]
@abhishekjain35 sure, go ahead!

**Comment by abhishekjain35** [comment]
Ok, thanks :+1:

**Comment by abhishekjain35** [comment]
@daltonfury42, I've fixed the **SidePanel** and also the **header** section (Check the images below). If you approve I Can make the PR. If you need any more changes, Please Describe.

![image](https://user-images.githubusercontent.com/53055241/95010663-c2c47900-0648-11eb-9bfe-637b029cff7a.png)

**AND**

![image](https://user-images.githubusercontent.com/53055241/95010673-d839a300-0648-11eb-8cb6-a88a39df417f.png)

**Comment by daltonfury42** [comment]
Yes, this is good. Let's make this change. Thanks!

**Comment by abhishekjain35** [comment]
Hey @daltonfury42 , I've made the PR. Please take a look.

**Comment by maaverik** [comment]
This looks good. Great job.

**Comment by abhishekjain35** [comment]
@maaverik and @daltonfury42 , Thanks. It was a great experience. :100:
