### ISSUE TITLE
[Admin dashboard]Add member button renaming

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#320]
Rename the join queue button to Add since this is within the admin dashboard  and  is misleading
Change text 
![image](https://user-images.githubusercontent.com/13188906/95010111-67908780-0644-11eb-93f3-d09391133f0d.png)

**Comment by daltonfury42** [comment]
I was also thinking of this.. This same text would also come in the join queue page, so we should do something neutral.

"Add", "Add to Queue" all works.

**Comment by sajmalyousef** [comment]
Add to Queue  is like stating the obvious? and longer ?

**Comment by daltonfury42** [comment]
Stating the obvious is fine? Long two word buttons == bigger buttons? That was my thought process, but anything is fine

**Comment by arkumari2000** [comment]
Can I do this if this is open and Add to Queue or Add is it?

**Comment by maaverik** [comment]
Hi @arkumari2000, a PR is already open for this pending some changes. Please take a look at the other open issues and see if there's something you'd like to work on.
