### ISSUE TITLE
Implement links on Homepage Navbar

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#321]
Our navbar has a few links, they have not been finished, it's just placehoders currently:

![image](https://user-images.githubusercontent.com/11256376/95010087-42037e00-0644-11eb-8eb2-ca4f0ab4fbdd.png)

My Queues and Sign-in are work in progress, in this issue we should implement:

1) Clicking on "How it works should scroll down to the "Create a Queue at the click of a button" section on the same page:

![image](https://user-images.githubusercontent.com/11256376/95010146-a8889c00-0644-11eb-9c23-f9b813eb5c59.png)

2) Similarly, clicking on "Contact Us" should scroll all the way down to the footer:

![image](https://user-images.githubusercontent.com/11256376/95010164-c6ee9780-0644-11eb-8cd1-464f5757fcfc.png)

**Comment by SuzannaWentzel** [comment]
Hi! Can I have a try on this one? I'm new to contributing to open source projects but this seems like something I should be able to do :).

**Comment by maaverik** [comment]
Sure. Go ahead.

**Comment by keithmchd48** [comment]
Hi! @maaverik I have submitted a PR to complete this feature https://github.com/SimplQ/simplQ-frontend/pull/329.

But there are some checks failing. Can you tell me how I can go about fixing them??

**Comment by gabrielatricak** [comment]
Hi, i would like to work on this for school project. Can I be assigned to this?

**Comment by maaverik** [comment]
@keithmchd48 has opened a PR for this already at #329. You can raise another PR if you have a different approach to this, otherwise it might just be wasted effort @gabrielatricak @SuzannaWentzel. If you have suggestions, please comment here or on the PR.

**Comment by daltonfury42** [comment]
@SuzannaWentzel @gabrielatricak Welcome. Would one of you like to work in increasing the whitespacing of the homepage sections discussed here? https://github.com/SimplQ/simplQ-frontend/issues/323

To avoid working on the same issue, one of you can comment on https://github.com/SimplQ/simplQ-frontend/issues/323 and take it up. Keep an eye on https://github.com/SimplQ/simplQ-frontend/labels/You%20Can%20Do%20This or follow the project to be notified of new issues.
