### ISSUE TITLE
Admin dashboard fix margin and spacing

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#325]
The current admin dashboard is spread far apart compared to original design. It looks a bit zoomed (1st image) and not as good as the  design ( 2nd image)
![image](https://user-images.githubusercontent.com/13188906/95011118-0f5d8380-064c-11eb-90e7-794f5ada458f.png)

![image](https://user-images.githubusercontent.com/13188906/95011148-492e8a00-064c-11eb-9437-c09a744675db.png)

Can it be centered maybe?
https://github.com/SimplQ was looking at this page , wherein things are centered a bit

**Comment by akashkbaburajan** [comment]
Yes, 2 other points I wanted raise are:
1. There are a few spacing issues compare to design for all those queue setting tiles on right side - spacing between "+" to "Add User Manually" to text under it.
2. Add user manually expansion should happen on clicking anywhere on the tile and not just on the "v"

**Comment by akashkbaburajan** [comment]
3. Refresh queue makes more sense to me than refresh status.
4. colour of refresh queue and copy to clipboard buttons should change
5. add user manually makes more sense than
![Uploading Adobe XD 04-10-2020 14_43_54 (2).png…]()
 add member

**Comment by akashkbaburajan** [comment]
3. Refresh queue makes more sense to me than refresh status.
4. colour of refresh queue and copy to clipboard buttons should change
5. add user manually makes more sense than add member
![Adobe XD 04-10-2020 14_43_54 (2)](https://user-images.githubusercontent.com/16539463/95011742-8eed5180-0650-11eb-87bb-18086a86b082.png)

**Comment by daltonfury42** [comment]
We should standardise and use the same margin that we use in home page (See https://github.com/SimplQ/simplQ-frontend/issues/327)

For the buttons, I feel the white background looks better, and also that's easier from implementation standpoint (Changing this would add extra complexity). So can we keep them as they are?

We should fix all the other points raised

**Comment by akashkbaburajan** [comment]
those colour differences were made to make the important button more catchy. I guess its fine to leave them white for now

**Comment by karthiksista** [comment]
I will be working on this.

**Comment by karthiksista** [comment]
Created a [PR](https://github.com/SimplQ/simplQ-frontend/pull/347) for this issue.

**Comment by daltonfury42** [comment]
Done
