### ISSUE TITLE
Standardise and Give a pagewide margin

### ISSUE THREAD

**Issue by akashkbaburajan** [SimplQ/simplQ-frontend#327]
Compared to design, website is cramped up in the middle. All sections need to be expanded so that blank space is not too much.
Top part is design and bottom is current website
![Adobe XD 04-10-2020 13_18_49 (2)](https://user-images.githubusercontent.com/16539463/95011573-441f0a00-064f-11eb-99bd-bc51946ae52a.png)

**Comment by daltonfury42** [comment]
Yes lets increase spacing, especially margins. Related discussion https://github.com/SimplQ/simplQ-frontend/issues/323

**Comment by daltonfury42** [comment]
Currently we have individual margin for each section. We should have one left and right margin for the whole page defined on the body or so. Then we should give negative margins for for components that go out (like the divs with a background colour in out design.

**Comment by karthiksista** [comment]
I would like to work on this.
Can I pick this one?

**Comment by daltonfury42** [comment]
@karthiksista This task might overlap with https://github.com/SimplQ/simplQ-frontend/issues/323 which someone else is already working on.

Would you like to take up the similar task for admin page instead? https://github.com/SimplQ/simplQ-frontend/issues/325

**Comment by karthiksista** [comment]
@daltonfury42 Ok sure. Will Do.
Thanks

**Comment by daltonfury42** [comment]
Raised PR for home page https://github.com/SimplQ/simplQ-frontend/pull/378
