### ISSUE TITLE
Contact Us form update

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#337]
This link can be used for the contact Us tab on the home page navbar. The content can be updated as required. 

https://iimb.qualtrics.com/jfe/form/SV_aY8FY91ztRX9NvD

![image](https://user-images.githubusercontent.com/13188906/95018904-038bb480-0680-11eb-9e1e-59c4db626dfd.png)

**Comment by daltonfury42** [comment]
This is looking like a survey. I feel we need just a simple contact us page:

```
Email:
What do you want to contact us about?:
```

**Comment by daltonfury42** [comment]
Also, clicking on contact us would scroll down to the footer, and we should keep another "contact us" link there to the form.

**Comment by sajmalyousef** [comment]
Haa cool this can be done. I was thinking of something like a help us improve too

**Comment by sajmalyousef** [comment]
This has been updated . Do check now

**Comment by daltonfury42** [comment]
Email, Subject and then something else other than "description" might be better.. How about "How can we help you?"

Once the form is filled, "We will respond to you shortly. Thank You!" is displayed. Can we customise this? Can we add a link to take the user back to home page?

**Comment by daltonfury42** [comment]
I've added the link here: https://daltonfury42-patch-1.dpmhbfuiok7f8.amplifyapp.com/ What do you think?

**Comment by daltonfury42** [comment]
Nice, I tried on the UI and it automatically redirected back to the old page.

**Comment by sajmalyousef** [comment]
its difficult to notice ? I think
 Can we just have contact us directly go there? I gave a return link on the form as well
I have changed the link to redirect to homepage

**Comment by daltonfury42** [comment]
Yes it's difficult to notice. Let me do this.

**Comment by daltonfury42** [comment]
I've made the changes, you can close this if it looks alright
