### ISSUE TITLE
[Mobile alignment] Realign the  buttons on admin dashboard

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#338]
Realign the Refresh status and Copy to clipboard buttons to center on mobile view
![photo_2020-10-04_21-02-02](https://user-images.githubusercontent.com/13188906/95019816-2a001e80-0685-11eb-9c74-79f6e4108b36.jpg)

**Comment by Gh05d** [comment]
I will do this.

**Comment by Gh05d** [comment]
I just realized that it would make sense to wait for the merge of pull request https://github.com/SimplQ/simplQ-frontend/pull/333 to implement this, as this could cause merge conflicts otherwise.

My question is whether I should just update that pull request or wait for the other to merge?

**Comment by daltonfury42** [comment]
I've merged https://github.com/SimplQ/simplQ-frontend/pull/333 you can raise a new PR.

**Comment by Gh05d** [comment]
Is this still an issue? It aligns nice now that #333 was merged.

**Comment by maaverik** [comment]
@sajmalyousef can this be closed now?
