### ISSUE TITLE
Admin page sidebar styling

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#342]
The add manually option has a collapsible form which has broken the styling of the sidebar.

![Screenshot from 2020-10-04 22-08-11](https://user-images.githubusercontent.com/12583528/95021404-68e6a200-068e-11eb-8170-0afe6b84492b.png)

The sidebar should be right aligned and the form should appear below the text as given here.

![Screenshot from 2020-10-04 22-10-11](https://user-images.githubusercontent.com/12583528/95021412-756afa80-068e-11eb-9918-2b625319b880.png)

https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/

**Comment by daltonfury42** [comment]
We should build our own expansion panel, and not use material ui components.

**Comment by daltonfury42** [comment]
I'll take this up

**Comment by daltonfury42** [comment]
I've raised a PR to fix this. https://github.com/SimplQ/simplQ-frontend/pull/345
