### ISSUE TITLE
Implement the queue details collapsible dropdown in status page

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#343]
The queue details button should open a dropdown with the details of the queue as given here.

![Screenshot from 2020-10-04 22-16-29](https://user-images.githubusercontent.com/12583528/95021561-45702700-068f-11eb-953a-f5ffd7d7b7b4.png)

Take a look at the commented part of src/components/pages/Status/QueueDetails.jsx to get an idea of the required data that comes from the backend. This same commented table has to be implemented to fit the above given design. The src/components/pages/Admin/AddMember.jsx file is a good reference to create a collapsible element.

**Comment by giubatt** [comment]
Can I get assigned to this?

**Comment by daltonfury42** [comment]
Sure, I have implemented a collapsable here, once this PR gets merged you can take this as reference for making the expansion panel: https://github.com/SimplQ/simplQ-frontend/pull/345/files

**Comment by maaverik** [comment]
You can follow the styling in the admin page, they look better imo. Making a generic component is a great idea. Please go ahead.
