### ISSUE TITLE
Non notifiable tokens bell icon change

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#353]
![image](https://user-images.githubusercontent.com/11256376/95115827-b54fe180-0763-11eb-8f00-1a869241608f.png)

When adding a token manually from admin page, we cannot notify them. The bell icon has a cross, but still it's not obvious because the icon has interactivity on hover.

In case of non notifiable tokens (handled [here](https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/pages/Admin/Token.jsx#L51)) we should not enclose it in a button group and also the bell icon should have a grey disabled color.

**Comment by daltonfury42** [comment]
@akashkbaburajan what do you say? Even I got confused because of the button feel, and was wondering why notifications were not working. People are absent minded, and they might try and notify and think that the token was notified, if it has hover effects and don't appear greyed out

**Comment by daltonfury42** [comment]
![image](https://user-images.githubusercontent.com/11256376/95663288-a8fcc780-0b5b-11eb-93b9-b0c481b8a2d8.png)

It's confusing for people we need to grey it out. On hover some tooltip should tell why it's disabled.

**Comment by sajmalyousef** [comment]
This needs to be addressed

**Comment by daltonfury42** [comment]
Done
