### ISSUE TITLE
Call button not working

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#354]
Pressing the call button on the token should open the dialer on the system:
<img width="1152" alt="Screenshot 2020-10-05 at 11 51 59 PM" src="https://user-images.githubusercontent.com/11256376/95117252-e6311600-0765-11eb-95b1-38584ef237ff.png">

https://stackoverflow.com/questions/17219688/href-tel-and-mobile-numbers

Since it's a onClick / button, we would have to do something like this:

https://stackoverflow.com/questions/23857507/how-to-trigger-a-phone-call-on-button-click-in-a-php-website/23857579

**Comment by sethbrotherton** [comment]
I'll give this a shot, if you don't mind.

**Comment by sethbrotherton** [comment]
PR up for this https://github.com/SimplQ/simplQ-frontend/pull/357

**Comment by daltonfury42** [comment]
Thanks @sethbrotherton
