### ISSUE TITLE
[Design] Sign in /Sign Up

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#359]
Just tried figma to create a sign in. This is just a rough one, can make it better. Was thinking of a pop up on click of the sign in button. Have just put the google auth option.
Was considering sign up through mobile number as well. Let me know your thoughts
![Capture](https://user-images.githubusercontent.com/13188906/95193122-ed513600-07f0-11eb-881b-d8e3645df374.PNG)
@daltonfury42 @akashkbaburajan @maaverik

**Comment by daltonfury42** [comment]
Do we need this page? 🤔

**Comment by sajmalyousef** [comment]
https://www.canva.com/ I was thinking of it like this?

**Comment by daltonfury42** [comment]
That makes sense when you want to add multiple options... I was thinking of just adding google directly for now.

We could design this, but then I was thinking later. First lets add one provider and make it work.

**Comment by sajmalyousef** [comment]
ok makes sense
