### ISSUE TITLE
[UX] Key Board Enter Should Do The Right Action

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#36]
For example, in the home page, when you type the queue name, and press enter, it should be as if the user had clicked on create queue.

Also, ensure that required fields are filled before allowing the button press. Else highlight that a field is required, or something like that.

Not just for create queue, but for add queue, and other pages as well.

**Comment by maaverik** [comment]
Done in latest new-frontend PR
