### ISSUE TITLE
Admin Ability to Pause and Resume Queue

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#362]
Implement Pause / Resume as per [design](https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/). 

![image](https://user-images.githubusercontent.com/11256376/111102947-43ca5980-8573-11eb-954d-cebd948eb18e.png)

The current design does not handle the queue paused scenario at the user's end:
 1. Given that the queue is paused from the admin dashboard by the queue admin 
 2. When a user tries to enter the join queue page using the queue link
 3. Then the page should display appropriate message as "Queue is paused, currently not accepting users"

**Comment by daltonfury42** [comment]
Blocked on pause queue feature. I have to merge a long due backend PR before we can pause queue. I'll do that next weekend

**Comment by daltonfury42** [comment]
When the user lands on the joining page, we make a call to the backend to get the queue details. The response now has a new "status" field which says if the queue is one of:
```
    ACTIVE,
    PAUSED,
    DELETED
```

Sample response:

```
{
   "queueId":"06e1376f-b802-4691-baa7-e7b4311e41a8",
   "queueName":"dasdadsads",
   "status":"ACTIVE",
   "numberOfActiveTokens":0,
   "totalNumberOfTokens":0,
   "queueCreationTimestamp":"2020-10-09T20:58:05.422+0000"
}
```

If the queue is active, the form is to be displayed. Otherwise we should display a message. @akashkbaburajan Do you want to design it, or I was thinking just a centered text and a button world do:
```
Hi! The queue is currently not accepting people. <Refresh Button>
```
or 
```
Hi! The queue you are trying to join has been deleted. <Home Button>
```

What do you think?

**Comment by mmendiratta** [comment]
Hello @daltonfury42, I am looking to pick up this issue. I have the project running locally now and wanted to know if there have been any changes since December, otherwise, I will get started on this. Thanks!

**Comment by daltonfury42** [comment]
Hi @mmendiratta Thanks for taking up this one. There would be other follow up tasks that you can do around this feature once this is done.

We are unblocked from the backend side. You can try creating a queue, and then send a post request to `/queue/<queue-id>` with the body:

```
{
  "status": "<new-status>"
}
```

where the `new-status` can be `PAUSED` or `ACTIVE`. Let me know if you face any issues.

**Comment by daltonfury42** [comment]
Currently it's a POST request, we will later change to a PATCH request, as it's more proper.

**Comment by daltonfury42** [comment]
Right. Two things:

1) Ability for admin to pause and resume the queue

2) Users should not be allowed to join a paused queue with a link, he
should be presented a message in place of the join form

**Comment by mmendiratta** [comment]
So admin is able to update the status of the queue, and I am able to get the user's end to read the status and update what they are seeing. One problem I am having is the state of `queueStatus` seems to be one state behind. I haven't used a lot of  `useSelector` so maybe if you have an idea of why this is happening that could help. Thanks.

**Comment by daltonfury42** [comment]
Can you raise a PR, and I’ll take a look

**Comment by daltonfury42** [comment]
@mmendiratta Good job on the pause queue PR. I think we don't really need the ribbon in the design, as the dark highlighted button does seem to do the job.
