### ISSUE TITLE
Explore and Integrate One Tap

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#389]
https://developers.google.com/identity/one-tap/web

This would greatly improve sign ups, we should definitely integrate this if possible: 

![image](https://user-images.githubusercontent.com/11256376/96557632-23ee7c80-12d8-11eb-996b-c4ce37e4b5ba.png)

If someone is already signed into google in their browser, they would be encouraged to login to our site too. And it's looking very neat and seamless.

**Comment by daltonfury42** [comment]
Our current Login Code:

https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/services/auth.js
https://github.com/SimplQ/simplQ-frontend/blob/new-frontend/simplq/src/components/common/LoginButton.jsx

**Comment by daltonfury42** [comment]
@Vishv07 This is looking very interesting, and I was planning to try this out next weekend. If you are interested, you can take this up ahead of me.

**Comment by Vishv07** [comment]
Seems like, there's already google stuff has been done, so we should configure now one tap. Thats what you thinking.

**Comment by daltonfury42** [comment]
I think you can explore one tap, see if it will augment the current setup.. but in case you feel that it will be a better replacement, we can do that. Let me know in a draft PR.

**Comment by daltonfury42** [comment]
@Vishv07 I'd prefer you replacing the current implementation with a cleaner one, if one tap provides one.

**Comment by Vishv07** [comment]
Okay, I'll have a look at this weekend @daltonfury42

**Comment by Vishv07** [comment]
@daltonfury42  Hey dude, I am not recovered yet. Really sorry that I couldn't able to give time to this task. will start working back once I'll be fine

**Comment by daltonfury42** [comment]
Sure, no problem. In the meantime, I was working on other aspects of the
site

**Comment by daltonfury42** [comment]
@Vishv07 are you still interested in taking this up?

For now I have hidden away the login button.

https://github.com/SimplQ/simplQ-frontend/commit/10e0db21124c19c59d9a23a66d4b88736f41166b

**Comment by Vishv07** [comment]
are you still working on this? @daltonfury42

**Comment by daltonfury42** [comment]
No, it's up for grabs

**Comment by daltonfury42** [comment]
I am going to give this a shot
