### ISSUE TITLE
Fix Sonarqube Reported Issues

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#406]
Sonarqube has reported some issues in our codebase, we should resolve them.

https://sonarcloud.io/project/issues?id=SimplQ_simplQ-frontend&branch=master&resolved=false&types=BUG

**Comment by rahulpatel596** [comment]
Hey @daltonfury42 I'd like to work on this

**Comment by daltonfury42** [comment]
Sure, this would be a good starter issue

**Comment by rahulpatel596** [comment]
Hey! I have applied fix on my cloned repo for most of those error except with missing backup/generic font-family. Is there is any specific preference or anything for generic font-family or should I just add Helvetica?

<img width="980" alt="Screen Shot 2020-11-02 at 11 07 04 PM" src="https://user-images.githubusercontent.com/33618437/97951546-22a16300-1d60-11eb-95b5-41330817e189.png">

**Comment by daltonfury42** [comment]
I’m not an expert at this, let’s go ahead with this.

Do a ‘yarn run lint’ to fix linting
