### ISSUE TITLE
Admin Page to Avoid refresh

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#41]

**Comment by daltonfury42** [comment]
As discussed, use web-sockets. In browsers where there is no websocket support, let's check and fall back to a refresh button? 

Blocked on backend support

**Comment by maaverik** [comment]
Will add a self refresh every few seconds as a temporary solution till websocket support is enabled on the backend.

**Comment by daltonfury42** [comment]
@maaverik If you think of it, a self refresh every 10s is simple, no complications, it would simply work.

A 10s delay in knowing that the user was notified is acceptable, in my opinion. Same with Admin view. What do you think?

**Comment by maaverik** [comment]
Sounds good

**Comment by thehamzarocks** [comment]
Yes, since we don't have requirements for low-latency or high volume transfers, we can stick to traditional polling.

**Comment by thehamzarocks** [comment]
A few questions:

1. Should we remove the refresh/check status buttons post this change?
2. Currently, if there's a network error, the error notification would keep popping up on every poll which is annoying. Can we change it to persist until the user closes it? It would pop up again though.

**Comment by daltonfury42** [comment]
1. Let them stay, so that people can play with them. It gives them something to do while waiting.

2. Yes. 

Also, try to use an axios interceptor and redux to centralise this. https://dev.to/teroauralinna/global-http-request-and-response-handling-with-the-axios-interceptor-30ae

3. Yes, we can do that. We need to make sure all these ideas are tracked. Can you create an issue for this and assign to @akashkbaburajan
