### ISSUE TITLE
Style Token Number display on Status Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#413]
Go to home page, create a new queue, copy the queue url and use it to join the queue. When you fill name and mobile number, you join the queue and reach the token status page.

Currently the token number is simply displayed:

![image](https://user-images.githubusercontent.com/11256376/98017167-e421ac00-1e24-11eb-8c97-f528c9fcff95.png)

Sample Page Link: https://www.simplq.me/token/1c2ad215-100e-489e-a44e-c1c36a854fc3

We need to change it as follows:

![image](https://user-images.githubusercontent.com/11256376/98016998-ac1a6900-1e24-11eb-9408-067fc009484d.png)

Design Link: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e87838cd-febc-4f37-a68a-9daa0d6b207b/specs/

**Comment by rahulpatel596** [comment]
@daltonfury42 Yeh, I'd like to work on this one.

**Comment by daltonfury42** [comment]
Awesome, what's your approach going to be?

**Comment by rahulpatel596** [comment]
I think it should be straight forward as information is already available there. I simply need to make some divs and give styling.

<img width="259" alt="Screen Shot 2020-11-05 at 5 39 06 PM" src="https://user-images.githubusercontent.com/33618437/98308503-d0de2000-1f8d-11eb-8e99-24e704a04c3b.png">

**Comment by daltonfury42** [comment]
👍 We can then `position: absolute` this to the parent div (the white main section, I think.

We would have to make it work on mobile after doing this, on mobile we will see if it's better to keep it positioned like that, or should we use media queries and center it or so. That call we can take once the component is done.

**Comment by rahulpatel596** [comment]
Hey @daltonfury42 
I have this UI almost ready. I am just wondering on top cap part of the threads, Do you have svg or something or should I may be add some stores to element or something.

<img width="381" alt="Screen Shot 2020-11-08 at 12 54 20 AM" src="https://user-images.githubusercontent.com/33618437/98459094-f66d5400-215c-11eb-962c-4677c94b1265.png">
<img width="619" alt="Screen Shot 2020-11-08 at 12 53 50 AM" src="https://user-images.githubusercontent.com/33618437/98459097-fcfbcb80-215c-11eb-85d2-f48d9e5c304e.png">

**Comment by daltonfury42** [comment]
We don't have it, if it's possible to have, let's do, but if it would take effort, I think what you have currently will work for us

**Comment by rahulpatel596** [comment]
@daltonfury42 Can you review my PR and close this issue and my PR. Thanks :)
