### ISSUE TITLE
Style Middle Section of Status Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#414]
The toke status page currently looks like this:

![image](https://user-images.githubusercontent.com/11256376/98017555-6f02a680-1e25-11eb-9927-78a5b56a914c.png)

The content of the card in the middle (outlined in red) needs to be styled as per the design to look like:

![image](https://user-images.githubusercontent.com/11256376/98017668-95284680-1e25-11eb-93bb-ae1abeacb7ac.png)

Design Link: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e87838cd-febc-4f37-a68a-9daa0d6b207b/specs/
Sample Status Page: https://www.simplq.me/token/1c2ad215-100e-489e-a44e-c1c36a854fc3

Go to home page, create a new queue, copy the queue url and use it to join the queue. When you fill name and mobile number, you join the queue and reach the token status page.

**Comment by maaverik** [comment]
This is partially done already except for the above screenshot where there's no one ahead of the user. In that case, we could make the text more appealing somehow. In other cases, it would look like this.
![Screenshot from 2020-11-03 23-21-11](https://user-images.githubusercontent.com/12583528/98022344-80e74800-1e2b-11eb-9d72-4e4882342af1.png)
The formatting doesn't match the design exactly, so there's a bit of work left there.

**Comment by daltonfury42** [comment]
Oh I see. This looks done to me, then. We should ask @akashkbaburajan to think about how to make it more attractive in the other states
