### ISSUE TITLE
Design: Section at the end to encourage people to try it out

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#416]
When the user scrolls down at the homepage, at the end, before the footer, we can keep one more block like this:

![image](https://user-images.githubusercontent.com/11256376/98242074-e5241c00-1f91-11eb-9c2b-1ef69509e2d0.png)

This might help a bit with conversion rate. Check out https://wistia.com/

**Comment by iamalexk** [comment]
Hi @daltonfury42 do you think I could give this issue a shot?

**Comment by daltonfury42** [comment]
Yes sure, we don't have designs ready for this section, but this is simple new section, so you can get creative.

**Comment by daltonfury42** [comment]
@iamalexk are you still interested in doing this?

**Comment by AleemRehman** [comment]
@daltonfury42 is this something I can pickup as first issue?

**Comment by daltonfury42** [comment]
Hi @AleemRehman This might be the easiest task you can take to get set up the code and warm up. Later you can move to #422

**Comment by AleemRehman** [comment]
@daltonfury42 I'll get to working on this ASAP and update you!

**Comment by AleemRehman** [comment]
@daltonfury42 what would you like these buttons to link to? Both the `create a queue` and `join a queue` buttons already exist on the page?

**Comment by daltonfury42** [comment]
Let's have a "Start Now" button, which on click will [smoothScrollToHomePageTop](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/common/utilFns.js#L24)

**Comment by daltonfury42** [comment]
Thanks, @AleemRehman for adding this section. Our master branch is deployed to https://dev.simplq.me so you can see your changes there.

![image](https://user-images.githubusercontent.com/11256376/103299568-da7e8400-4a22-11eb-9d95-41b234a2f6d3.png)

Do you think this svg will look good in the background of the section? @AleemRehman

**Comment by AleemRehman** [comment]
@daltonfury42 I think it would make sense if the SVG didn't incorporate the ATM element too. The graphical style isn't really in line with the graphics used on the rest of the page either, some examples I'm referencing here:
<img width="1611" alt="Screenshot 2020-12-29 at 19 23 36" src="https://user-images.githubusercontent.com/18561224/103308893-7c927200-4a0b-11eb-9b00-ce5add69d753.png">
