### ISSUE TITLE
Implement Admin Page Tutorial

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#423]
There is a tutorial on visiting the admin page for the first time. This is an independent task that can be taken up:

![image](https://user-images.githubusercontent.com/11256376/101764516-2a45eb80-3b06-11eb-94a7-9ad9ff1af510.png)

How to do this, we need to figure it out. 🤔 

[Design Link](https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/95f74aec-6b57-4ddd-bcf1-97bb5a8786f8/)

**Comment by promarcussmith** [comment]
I can take this up   @daltonfury42
 I have two options

1)   [**ReactTour**](https://www.npmjs.com/package/reactour).
2)   [**React-Joyrid**e](https://www.npmjs.com/package/react-joyride).

my vote goes to ReactTour.

Let me know your thought on this.

**Comment by daltonfury42** [comment]
Sure, let's use ReactTour. I'd suggest breaking this into multiple PRs, for the first PR, keeping it simple, how about:

Step 1: Add people to the queue manually
![image](https://user-images.githubusercontent.com/11256376/104836388-a8e73300-58d3-11eb-9ca9-27ab322da364.png)

Step 2: Share your queue with others if you want people to join on their own
![image](https://user-images.githubusercontent.com/11256376/104836422-de8c1c00-58d3-11eb-8e31-48dd0badb32b.png)

Let's store a flag in the local storage indicating the user had already been presented with the tour, so that it doesn't come up again. If this works out well, we can later send the flag to the backend.

This is what I have in mind, but if you have other ideas, you can try those as well. Thanks.

**Comment by promarcussmith** [comment]
Agree with you. Working on it.

**Comment by promarcussmith** [comment]
@daltonfury42 
I have Implemented the discussed tour guide.

Changes available on  promarcussmith:tourGuideImplementation

![image](https://user-images.githubusercontent.com/77528300/105389319-b5ee8400-5c3d-11eb-93af-d9133dc9b4cd.png)

![image](https://user-images.githubusercontent.com/77528300/105389575-fcdc7980-5c3d-11eb-8b54-ffc496ac8887.png)

**Comment by maaverik** [comment]
This has been partially implemented so closing. We can open another issue later for any more specific hints we need.
