### ISSUE TITLE
Show Queue Stats On Queue Joining Page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#424]
It will be good to show the total number of people in the queue, before the user joins the queue. We could show the entire queue stats in the joining page.

**Comment by sajmalyousef** [comment]
Sounds like a great idea , this would help people avoid crowded places

**Comment by maaverik** [comment]
https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/e654742e-fb91-4a5c-83d6-4dff807e03ea/?fullscreen

It's part of the original design, we just hadn't gotten around to it. @sajmalyousef, the intent of simplq is for people to not have to go anywhere till their turn is up, whether it's crowded or not, right?

**Comment by daltonfury42** [comment]
While someone can always use SimplQ for getting people to join remotely and
arrive just in time, I think it’s practically difficult for a traditional
business to adapt this model. There could be other scenarios where you
remotely wait in a queue, though.

This is just my view, but our goal should be to keep the product as generic
as possible, so that anyone can use it in any way they want.

**Comment by daltonfury42** [comment]
Go to home page and join an already created queue, like 'aa'. Currently the gage looks like this:

![image](https://user-images.githubusercontent.com/11256376/104817469-77c12100-5847-11eb-9155-07ee4dba004d.png)

When the page is loaded, we are already fetching the required stats for the queue from the backend:

```
/v1/queue/status?queueName=aa
{
   "queueId":"49b1ffa6-87fd-4a46-b95f-5588711cecca",
   "queueName":"aa",
   "status":"ACTIVE",
   "numberOfActiveTokens":0,
   "totalNumberOfTokens":0,
   "queueCreationTimestamp":"2020-12-15T08:07:55.374+0000"
}
```

We need to define a new component and use it in [here](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/pages/Join/index.jsx).

![image](https://user-images.githubusercontent.com/11256376/104817760-39c4fc80-5849-11eb-9b4a-96224e514876.png)

**Comment by mradenovic** [comment]
Queue Stats data already appears in [QueueDetails](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/pages/Status/QueueDetails.jsx) component. I could extract it and make a reusable component to be used in Join and Admin pages:

```
      <div className={styles['detail']}>
        <DetailRow
          title="People currently in queue:"
          value={queueStatusResponse?.numberOfActiveTokens}
          large
        />
        <DetailRow title="Queue creation time:" value={creationTime} />
        <DetailRow
          title="Total number of people joined in queue:"
          value={queueStatusResponse?.totalNumberOfTokens}
        />
      </div>
```

**Comment by daltonfury42** [comment]
I see, right. We should refactor this out, fix the alignment and reuse it. 

![image](https://user-images.githubusercontent.com/11256376/105574885-6919c300-5d8d-11eb-8d41-2f202648cf6e.png)

I feel also that the Queue Details should be expanded by default, if you are going to work on this, you can take care of it?

**Comment by mradenovic** [comment]
👍 I started working in it.
