### ISSUE TITLE
Add Configurable Max Queue Capacity Limit

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#425]
Admin can optionally configure a max capacity, after which new people will be put on hold.

This might add value in certain situations, but I am a bit reluctant, as it's not a core feature. For example, admin can also adjust without it, I feel.

**Comment by daltonfury42** [comment]
We should have a new right side panel button to open a settings dialogue box, in which we can add this as a optionally configurable entry.

Right now the modal would look empty with just one configuration item, but soon we will add more.

![image](https://user-images.githubusercontent.com/11256376/111103509-a3753480-8574-11eb-820e-6926ad7211c7.png)


To set the max queue capacity, send a patch request to `/queue/{queueId}`, example payload:

```
{
  "maxQueueCapacity": <some-number>
}
```

Currently we have not handled the case at backend side where we need it to be unlimited, so we can set a very high value say 100000 for now when the user un sets it.

**Comment by maaverik** [comment]
Closed by #603
