### ISSUE TITLE
Integrate QR Code to share queue link

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#430]
Just like "Copy to Clipboard", I am thinking of having a "Generate QR Code" button, that will generate a printable QR code that the admin can take and send to people or print and stick somewhere if they want to.

![image](https://user-images.githubusercontent.com/11256376/103101973-f7d8da00-463f-11eb-8240-3e6fbbb910c7.png)

We will have to find and integrate a library that will generate QR codes.

**Comment by daltonfury42** [comment]
https://qrcode.tec-it.com/en/Url

**Comment by Vigenh199** [comment]
Hi, can I be assigned to this issue?

**Comment by daltonfury42** [comment]
Sure go ahead, we don't generally assign issues, but if you send a PR, it will be accepted. 

When you scroll down to the footer on any page, there is a link to the [Terms of Service](https://www.simplq.me/privacy#terms-of-service) page. I am thinking that you take the page as a reference, and build a similar component/page for displaying a QR code. Code is [here](https://github.com/SimplQ/simplQ-frontend/tree/master/simplq/src/components/pages/TermsOfService).

After the "SimplQ" Header with logo, content can be something like this:

![image](https://user-images.githubusercontent.com/11256376/103498290-39505d00-4e6a-11eb-8440-5d485ac1d6fe.png)

What do you think?

**Comment by Vigenh199** [comment]
Thank you for reply, I will try to solve this issue
