### ISSUE TITLE
Temporary Queue Warning for Unregistered Users

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#439]
![image](https://user-images.githubusercontent.com/11256376/102719374-baa8db00-4313-11eb-88b4-4c4463595c02.png)

Display a ribbon on admin page if the user has not logged in. The text can be fixed later. 

Use `isLoggedIn()` in [auth.js](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/services/auth.js) to check if user is logged in or not.

[Design Link](https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/) 

Design show it as above navbar. But keeping it above the navbar might be a bit more complex, so we can display the ribbon below the header section:
![image](https://user-images.githubusercontent.com/11256376/104058213-62317300-5219-11eb-84d6-6c498228eaca.png)

**Comment by yahsashay** [comment]
** want  to work on this issue **
we want only the orange color ribbon, not the text and a cross button

**Comment by daltonfury42** [comment]
Sure go ahead. This is a easy issue that can get you started.

We can have the ribbon, the text as in the design and the close button.
Let’s keep the same text as in the design, it can be modified later.

**Comment by shubh128** [comment]
I would like to work on this issue if it's not already being resolved

**Comment by daltonfury42** [comment]
Yes, you can take this up. @yahsashay has not send in a PR yet.

**Comment by shubh128** [comment]
![image](https://user-images.githubusercontent.com/48080672/103174811-21d20c80-488b-11eb-8288-672cc712db7f.png)
I was able to show a warning with this design. However I'm unable to match the exact design required as I can't figure out the CSS. Let me know if this design works for you or if you can help me with the CSS.
Also I was getting some errrors due to CORS being blocked.

**Comment by daltonfury42** [comment]
Send a PR, this is looking just great. I will review it there.

Tiny change: I guess keeping it on top might not be straightforward.  We can display the ribbon it between the navbar and the violet region (above the title). That way you don't have to position it absolutely.

Can you show me the CORS error, few screenshots would help.

**Comment by shubh128** [comment]
![image](https://user-images.githubusercontent.com/48080672/103193229-d4dd4d00-4901-11eb-9947-9c9ae55ea182.png)
I get this error when opening the queue page without signing in.
![image](https://user-images.githubusercontent.com/48080672/103193261-ed4d6780-4901-11eb-89b7-df737cbbe08a.png)
I encounter this error when signing in after creating the queue.

I have sent a PR. You can review the changes I have made

**Comment by maaverik** [comment]
@daltonfury42, I believe this error is specific to firefox and it's way of handling CORS. I usually see it too while running locally. @shubh128, could you try opening the app in chrome for debugging. I never have this problem in chrome.
