### ISSUE TITLE
Buttons on Hover should change pointer to Hand symbol

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#450]
![image](https://user-images.githubusercontent.com/11256376/104032032-92661b00-51f3-11eb-964d-b50b73749aec.png)

On hovering over our standard buttons, the mouse pointer doesn't change like in normal buttons.

**Comment by Harshit850** [comment]
@daltonfury42 will fix it.

**Comment by daltonfury42** [comment]
Hi @Harshit850 I accepted #451.

If you'd like to contribure, do you want to take over https://github.com/SimplQ/simplQ-frontend/pull/442?

**Comment by Harshit850** [comment]
> Hi @Harshit850 I accepted #451.
> 
> If you'd like to contribure, do you want to take over #442?
Thanks for asking but currently i am working on some other project, once it's done i will get back to #442
