### ISSUE TITLE
The pencil tool in the queue view page should have a tooltip 

### ISSUE THREAD

**Issue by oysters76** [SimplQ/simplQ-frontend#455]
The pencil icon in the queue view page is a bit confusing. When the queue is empty, you can 
click on the pencil icon, but it doesn't give any response. There is also no tool-tip to specify what 
it is meant to do. 

Maybe when the pencil tool is clicked, the name of the queue should be editable. If the tool is not meant to
be clickable at that stage, maybe it should be disabled? However, I think it is best if there was a tool-tip 
displayed to the user, explaining the purpose of the clickable component.  

I checked to see if I am getting any errors in the browser console, when I checked that the pencil tool is
not responding, but I found no errors there.  

Thanks 
![image](https://user-images.githubusercontent.com/75514064/104323054-b5524100-550b-11eb-9d6a-b0a1cad57970.png)

**Comment by daltonfury42** [comment]
Right, this and there are two more ([Pause Queue](#362) and Queue History) other interactive elements in the page that is there as per the design, but I never implemented. 

We should remove the pencil button from the header, as there is no backend support for it, and I don't think it adds a lot of value.

**Comment by oysters76** [comment]
I think the pencil tool would be useful in editing the queue name, I think it would improve the user experience.

**Comment by oysters76** [comment]
Would it be possible for me to implement this? Is there back-end functionality to edit the queue name?

**Comment by oysters76** [comment]
@daltonfury42  I went ahead and removed the pencil tool icon from the page. Thanks

**Comment by daltonfury42** [comment]
Thanks to you. The idea behind the pencil was to edit and add a queue description. Which will be visible to people who join/wait in the queue. But there was no backend support added for it.

You can take a stab at #362 if you are interested.
