### ISSUE TITLE
QR Code Modal Should Have a Close Button

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#459]
Go to https://dev.simplq.me After you create a queue and click on the modal to generate the QR code, we need to have a "Close" Button next to the "Print" button.

![image](https://user-images.githubusercontent.com/11256376/104407513-c04ab700-5587-11eb-8115-25df7bc2751d.png)

This is required as, on smaller screens, this Modal takes up full screen space, and it's difficult to close it:

![image](https://user-images.githubusercontent.com/11256376/104407663-1fa8c700-5588-11eb-922c-b8500702ddd9.png)

Also we can add a linebreak between "or visit" and the url.

**Comment by prabureddy** [comment]
Ok, I will work on this...
