### ISSUE TITLE
"Login Failed. Please try again" PreventDefault

### ISSUE THREAD

**Issue by abhishekpatel946** [SimplQ/simplQ-frontend#461]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.simplq.me/'
2. Click on 'Home'
3 See error 'Login Failed. Please try again.'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46045014/104463193-7984ad80-55d7-11eb-971d-b65dd4ef249a.png)

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Chrome]
 - Version [87]

**Additional context**
On the Landing page unexpected `Login Failed. Please try again.` or when I click on `Home` the same error prompt opens. I think when I landed or refresh the page the form will be submitted by default. Prevent this kind of uncertain form or click.

**Comment by daltonfury42** [comment]
Thanks @abhishekpatel946 for reporting this. I can reproduce the issue on Incognito.

**Comment by prabureddy** [comment]
@abhishekpatel946 Everything works fine in my system. Clear your cache, site settings and check again.

**Comment by daltonfury42** [comment]
Definitely we need better error here. I've raised #462 once that goes in, we will get more logging. On Incognito login fails due to cookies not being enabled, we will have to figure it out later.


![image](https://user-images.githubusercontent.com/11256376/104497911-0b54e080-5601-11eb-9b71-6804f8e6b883.png)

**Comment by daltonfury42** [comment]
@abhishekpatel946 Can you try reproducing the issue on https://dev.simplq.me?

**Comment by abhishekpatel946** [comment]
**I got the point of the problem.**

> If we want to `Block third-party cookies` or `Block all cookies (not recommended)` in chrome.
> Then the `Login Failed. Cookies are not enabled in current environment`. Prompt is activated.

![image](https://user-images.githubusercontent.com/46045014/104541455-ab355d00-5647-11eb-8220-8d8a7eb7f62a.png)


_but if we `Allow all cookies` in Chrome then the prompt is not active._ 
**Note:-** Same thing happens in the incognito mode in Chrome.

**Comment by abhishekpatel946** [comment]
> Thanks @abhishekpatel946 for reporting this. I can reproduce the issue on Incognito.

sure :+1:

**Comment by maaverik** [comment]
What would be the best way to suppress this error message for us? Should we just pass an extra argument to skip the handleApiErrors call in case this particular situation occurs?

**Comment by daltonfury42** [comment]
@maaverik This is not our API failing, but the google login library reporting a failure when trying to login. We should not suppress this message, but show it to the user, right? So that he enable cookies to login (which is saaad)

**Comment by maaverik** [comment]
It makes sense to show this if he tries to login, but this shows up if a user simply opens the site, which ruins user experience in my opinion. Can we modify that initial login attempt somehow? 

As for the message, can we change it to something like "Please enable cookies in your browser to login"?

**Comment by daltonfury42** [comment]
I see. If we disable it, we will have to see how login will happen when the user refreshes the page. 🤔

**Comment by maaverik** [comment]
We don't need to disable it. I was thinking we could make error reporting optional for the initial login attempt on page load. Let it fail silently the first time the page loads.

**Comment by daltonfury42** [comment]
ACK. We should do that. Don't know how to detect this, have to check

This is not a axios request. It's happening [here](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/common/LoginButton/index.jsx#L30).

**Comment by daltonfury42** [comment]
We could have a flag, and suppress the first time this happens. In case of affected users, first time should always be on page reload. We could do this with some flag, but just that we are doing a hack to cover up a bug. Server side OAuth flow might be a big task, but has a cost/complexity. Or we would have to think of a different auth provider that can give us google sign in, I don't know.

**Comment by maaverik** [comment]
Let's go with the flag. Things are pretty simple and secure with google sign-in and so far, this is the only problem, right? I think it's tolerable.

**Comment by daltonfury42** [comment]
Summarising the discussion with @maaverik, we might be better off integrating to some other provider for auth, and he suggested [Okta](https://www.okta.com/). 

I was checking it out, and Google doesn't provide SPA/React specific integration, but Octa does. So Octa might be cleaner to integrate, only that we have to pay after more than 1000 active user logins per month. This is good enough for us to evaluate.

**Comment by daltonfury42** [comment]
While google has not cared to solve it in their client library, I can see that octa is trying to solve this as a Early Release feature.

![image](https://user-images.githubusercontent.com/11256376/105575756-e0eaec00-5d93-11eb-82eb-72bdbf23dab4.png)
