### ISSUE TITLE
Copy link should copy pure link not with some extra words

### ISSUE THREAD

**Issue by Vishv07** [SimplQ/simplQ-frontend#480]
```
Hi! Use https://www.simplq.me/j/dfgbfhb to join my queue and get live updates.
```

This is what the Copy Button does
Instead of this, we can just copy the url alone
```
https://www.simplq.me/j/dfgbfhb
```
@daltonfury42

**Comment by daltonfury42** [comment]
Me and @sajmalyousef made it like this to record a demo video once. In the video, the user copied the link and shared it over Whatsapp. 

Copying the url alone makes sense when you want to paste it in a new tab, but this won't be used by a real user. 

cc @maaverik

**Comment by Vishv07** [comment]
That's Okay too.

I was comparing it with google meet's  copy URL process, We get URL only

This is also cool👍

**Comment by daltonfury42** [comment]
I just checked Google Meet, previously they were also adding some text, if I remember correctly.. but they seem to have moved to what you have suggested. 

I'll close the issue for now, thanks!

**Comment by mradenovic** [comment]
@daltonfury42 I was confused with this too. It's just about wording.

**Copy Link:** `https://www.simplq.me/j/SarmagedonIII`
**Share:** `Hi! Use http://localhost:3000/j/Sear to join my queue and get live updates.`

**Comment by maaverik** [comment]
Calling the button Share instead of Copy Link does make more sense.

**Comment by Vishv07** [comment]
Exactly! @maaverik

**Comment by daltonfury42** [comment]
My thoughts:

"Share" has a slightly different meaning, it's generally to share to share via social media or some other app, especially on mobile. I feel we should not use the overloaded word "Share"

"Copy Link" is more clear as to what the button will do. It copies the link to clipboard. I guess you guys are right, we should just copy the link alone and not put the extra words.

I was looking at some other products that I use, which has a copy link functionality, some have both copy and share as different functionalities.

1) Loom

![image](https://user-images.githubusercontent.com/11256376/106347928-47b65b00-62e8-11eb-8469-25ec0718f7d1.png)

2) Google Meet:

![image](https://user-images.githubusercontent.com/11256376/106348073-5a7d5f80-62e9-11eb-9ca1-372398e36e3c.png)

3) Jitsi

![image](https://user-images.githubusercontent.com/11256376/106348085-800a6900-62e9-11eb-9ec7-cb9cc9826809.png)
4) Google Forms

![image](https://user-images.githubusercontent.com/11256376/106348097-a03a2800-62e9-11eb-9034-ed54a7d69e5b.png)

**Comment by maaverik** [comment]
How about having both copy link and share buttons like we see in the images above? We could implement the share button using something like https://www.npmjs.com/package/react-share. This way, the word share adheres to its usual meaning. And then the copy link button can be modified to give just the link.

**Comment by Vishv07** [comment]
That will work nice @maaverik

**Comment by daltonfury42** [comment]
Agreed. Can you create a task for this?

Then as a follow up, should we redesign this area:

![image](https://user-images.githubusercontent.com/11256376/106466232-1644b780-64c1-11eb-87ec-b7657a20fbad.png)

Too many big buttons :p

**Comment by maaverik** [comment]
I'll make a task for the share button. I agree that one more button ruins the layout. Let's maybe brainstorm different layouts here for now.

**Comment by prabureddy** [comment]
PR raised #510

**Comment by daltonfury42** [comment]
This is resolved. Now we copy just the link, and there is a separate way to share the link as well. Thanks everyone for the thoughts and @prabureddy for the implementation, this is now looking good.
