### ISSUE TITLE
Streamline naming convention

### ISSUE THREAD

**Issue by mradenovic** [SimplQ/simplQ-frontend#492]
- All filenames except index.jsx should be in PascalCase (i.e. Join.jsx, Join.module.scss, Form.jsx)
- Use index.jsx to re-export classes from the folder
- Match route path with component name
```html
<Switch>
    <Route path="/queue/:queueId" exact component={AdminQueue} />
    <Route path="/queue/:queueId" exact component={QueueById} />

    <Route path="/j/:queueName" exact component={JoinQueueWithDetails} />
    <Route path="/j/:queueName" exact component={JoinQueueByName} />

    <Route path="/token/:tokenId" exact component={QueueStatus} />
    <Route path="/token/:tokenId" exact component={TokenById} />

    <Route path="/privacy" exact component={TermsOfService} />
    <Route path="/legal" exact component={Legal} /> <!-- Split PrivacyPolicy and TermsOfUse -->
</Switch>
```

Make small changes in the following order to avoid too much turbulence (pun intended 😄 ):
- [x] Components
- [x] Pages
- [x] Layout (matching should be done last)
- [x] Actions and request Factory

**Comment by maaverik** [comment]
The only thing about this issue I have doubts about is 'Match route path with component name'. e.g., `Route path="/queue/:queueId"` points to the queue admin page (hence the component is named AdminQueue, we could shorten to Admin too), which requires a queueId to fetch info. Changing meaningful component names just to make it match the route name seems like overkill to me.
