### ISSUE TITLE
Use absolute imports

### ISSUE THREAD

**Issue by mradenovic** [SimplQ/simplQ-frontend#501]
Based on [docs](https://create-react-app.dev/docs/importing-a-component/#absolute-imports) and [research](https://stackoverflow.com/a/59195974/7234270) this:

```jsx
// relative imports hell
import StandardButton from '../../common/Button';
import { smoothScrollToHomePageTop } from '../../../utils/scrollingOperations';
```

can be turned this:

```jsx
import StandardButton from 'components/common/Button';
import { smoothScrollToHomePageTop } from 'utils/scrollingOperations';
```

**Comment by daltonfury42** [comment]
Thanks, I didn't know this.

https://hackernoon.com/react-pro-tip-use-absolute-imports-for-better-readability-and-easy-refactoring-2ad5c7f2f957
