### ISSUE TITLE
Home Page sends https request in a loop

### ISSUE THREAD

**Issue by mradenovic** [SimplQ/simplQ-frontend#503]
**Describe the bug**
After landing on a homepage, the page keeps sending `Request URL: https://devbackend.simplq.me/v1/queues` infinitely. I think it was introduced with PR #488.

**To Reproduce**
1. Go to `http://localhost:3000/
2. Open dev tools Networking tab

**Expected behavior**
I would expect page to make one request and display the data.

**Screenshots**

![image](https://user-images.githubusercontent.com/10821730/106278339-91c80f80-6208-11eb-93b8-67f157908fef.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 87

**Comment by daltonfury42** [comment]
Yes, this should be my recent change. I can take a look in a few hours.
