### ISSUE TITLE
Add a new button on the admin page to share queue info to different platforms

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#509]
Right now, we have a "copy queue link" button on our admin page that copies text in the form `Hi! Use https://www.simplq.me/j/dfgbfhb to join my queue and get live updates.` to the clipboard. The user then shares this link manually on different apps or paltforms. 

Let's create a new button called `Share` that opens up a dialog showcasing different social media buttons and allowing the user to share the queue information directly to those platforms.  We could use packages like https://www.npmjs.com/package/react-share or https://www.npmjs.com/package/react-social-sharing or something similar. Ideally, we want to showcase some popular platforms like facebook, twitter etc. when users click it on their desktop while on mobile, all communication apps installed should show up.

There's a related discussion [here](https://github.com/SimplQ/simplQ-frontend/issues/480#issuecomment-770161075). Let's start by deciding how the dialog should look like and what buttons to show on desktop use. Then let's figure out how to display all installed communication apps to be shown to the user on mobile.

**Comment by Vishv07** [comment]
I'll Open the PR this weekend 👍

**Comment by prabureddy** [comment]
PR raised #510
