### ISSUE TITLE
Footer doesn't stay at the bottom of Safari

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#511]
**Describe the bug**
Footer is coming on the landing page.

**To Reproduce**
Open https://dev.simplq.me on Safari

**Expected behavior**
Footer should be at the bottom of the page, seen only on scrolling to the end.

**Screenshots**
![image](https://user-images.githubusercontent.com/11256376/106630044-790d8000-65a1-11eb-88ce-3d2ffc55c175.png)

**Environment (please complete the following information):**
 - OS: iOS, OSX
 - Browser Safari

**Comment by arkumari2000** [comment]
Is this issue still there? Can I give it a try?

**Comment by daltonfury42** [comment]
This will be resolved by #512
