### ISSUE TITLE
Add Github Star Button to UI

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#514]
https://buttons.github.io/

We could add a star button to the UI somewhere. One option is to keep it on the navbar. Thoughts?

**Comment by Vishv07** [comment]
don't you think it'll look weird on the navbar ?

Umm, We can keep that on the footer or somewhere else?

**Comment by daltonfury42** [comment]
I've seen if before on some sites, I tried looking for it, but could not find it. Let me see if I get a example.

**Comment by rafaelcsva** [comment]
here we've an example [akveo](https://akveo.github.io/nebular/)

**Comment by daltonfury42** [comment]
@Vishv07 is right, it might look a bit weird on our navbar. I'm thinking of dropping the idea.

**Comment by maaverik** [comment]
What are your thoughts on something like this? https://tholman.com/github-corners/. I really like the animation.

**Comment by daltonfury42** [comment]
I'm liking it. We could try.

**Comment by Vishv07** [comment]
I'll give it a shot
