### ISSUE TITLE
Move app logic into redux

### ISSUE THREAD

**Issue by mradenovic** [SimplQ/simplQ-frontend#516]
# Move app logic into redux

This can be done partially in small chunks. it would be nice to rename the Request Factory functions.
I'm not sure if the `fetch` or `get` prefix would be better for async actions.

```js
QueueRequestFactory.getStatusByName(queueName)
RequestFactory.getQueueStatusByName(name)

QueueRequestFactory.get(queueId)
RequestFactory.getQueue(id)

// Final action call
dispatch(fetchQueue(id))

//or
dispatch(getQueue(id))
```

## How to do it

For every server request:
- Create a new issue for the task and assign yourself or ask a maintainer to do so.
- Rename (or better recreate) request-factory function to properly represent the action.
- Make an async action matching the request name similar to `getQueueStatusByName` in `store/asyncActons/getQueueStatusByName.js`. Export action in `store/asyncActions/index.js.js`.
- Add nice `jsDocs` to make IntelliSense useful.
- Create reducers for the needed state.
- Redesign components to use redux state and actions.

### Queues

- [x] `getUserQueues()`
- [x] `createQueue(name)`
- [x] `getQueue(id)`
- [x] `getQueueStatus(id)`
- [x] `getQueueStatusByName(name)`
- [x] `deleteQueue(id)`
- [x] `joinQueue()`

```
// Get metadata for all queues creaetd by the current user
export const getMyQueues = () => ({ method: 'get', url: '/queues' });

// Create a new queue
export const create = (queueName) => ({ method: 'post', url: '/queue', data: { queueName } });

// Get a queue by id. Returns all active tokens in the queue
export const get = (queueId) => ({ method: 'get', url: `/queue/${queueId}` });

// Return public stats for the queue, like number of people currently in the queue etc.
// This endpoint can be envoked by non-owners as well.
export const getStatus = (queueId) => ({ method: 'get', url: `/queue/status?queueId=${queueId}` });

// Same as getStatus, but fetch by name instead of ID.
export const getStatusByName = (queueName) => ({
  method: 'get',
  url: `/queue/status?queueName=${queueName}`,
});

// Delete a queue by ID
export const deleteQueue = (queueId) => ({ method: 'delete', url: `/queue/${queueId}` });
```

### Tokens

- [x] `createToken(id)`
- [x] `getToken(id)`
- [x] `notifyToken(id)`
- [x] `deleteToken(id)`

```
// Get a token by ID
export const get = (tokenId) => ({ method: 'get', url: `/token/${tokenId}` });

// Notify a token This will result in the user being notified by SMS, which is an upcoming feature
export const notify = (tokenId) => ({ method: 'put', url: `/token/notify/${tokenId}` });

// Remove a token from the queue. Can be called only by the person who created the token, and the queue manager.
export const remove = (tokenId) => ({ method: 'delete', url: `/token/${tokenId}` });
```
## Reducers to create

- [x] `queues' or 'userQueues` - Authenticated user queues. 
- [x] `queueStatus` - Once we have queues in the store there is no reason why the user couldn't switch between his queues without going to the home page and sending a new request to the server.
- [x] `tselectedQueue` based on `selectedQueue`.
- [X] Anything else that might come up.

## Components to refactor

The list will be long and volatile 😄 

- [X] `MyQueues` - To be renamed to `UserQueues`? (https://github.com/SimplQ/simplQ-frontend/issues/517)
- [x] Join Page (https://github.com/SimplQ/simplQ-frontend/issues/518)
- [x] Join Form
- [x] HomePage
- [x] StatusPage
- [x] AdminPage

**Comment by daltonfury42** [comment]
I will take up and finish some components, but can start only this weekend.

**Comment by daltonfury42** [comment]
I am taking up [token status page](https://github.com/SimplQ/simplQ-frontend/tree/master/simplq/src/components/pages/Status).

**Comment by maaverik** [comment]
Let me try working on the admin page.

**Comment by mradenovic** [comment]
I believe we are done here. If anything needs fixing, a new issue should be opened.

**Comment by daltonfury42** [comment]
This was a massive change, it's an enabler for us to do a lot of things with ease in the future. 

@mradenovic Thank you for this! 🙏
