### ISSUE TITLE
Fix Sonarqube reported Code Smells

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#548]
We have accumulated some easy to fix security vulnerabilities over the last few months over [here](https://sonarcloud.io/project/security_hotspots?id=SimplQ_simplQ-frontend&branch=master&resolved=false&types=SECURITY_HOTSPOT#). 

These are straightforward easy fixes, good for a new comer to take up as a good first issue. 

Once they are fixed, we should see if a branch protection rule can be set to catch them pre-merge

**Comment by hallelshohat** [comment]
I've made a pull request solving this issue

**Comment by daltonfury42** [comment]
Thanks @hallelshohat for fixing the security hotspots. Now what is left is some code smells that if anyone is interested, can go through and fix.

https://github.com/SimplQ/simplQ-frontend/pull/557

**Comment by daltonfury42** [comment]
I have gone through the list of issues and resolved a few as false positive after our discussions on https://github.com/SimplQ/simplQ-frontend/pull/564

@maaverik @mradenovic If you get time, go through the codesmells and let me know if we need there are any more such false positives

**Comment by skShekhar** [comment]
@daltonfury42 Are there anymore code smells or can this issue be closed?

**Comment by maaverik** [comment]
Hey @skShekhar. Sorry, missed your comment here. There are still a few small issues left, like the many TODOs we have. Let's leave this open so that we at least have a tracker that we can look at.

**Comment by Mogakamo** [comment]
Hey @daltonfury42 I'm new to open source and I wanted to tackle this issue.
I was hoping you could give me a heads up on how I could tackle this one.

**Comment by daltonfury42** [comment]
Hi @Mogakamo welcome. Here is a list of tiny tech debts that you can solve:

https://sonarcloud.io/project/issues?id=SimplQ_simplQ-frontend&open=AXfKRRGH1JV0IME_FJy0&resolved=false
https://sonarcloud.io/project/issues?id=SimplQ_simplQ-frontend&open=AXhz9D02G5SMudjmecKx&resolved=false
https://sonarcloud.io/project/issues?id=SimplQ_simplQ-frontend&open=AXe6u56LmUtjMyP-a6uc&resolved=false

After that, you can take up a bigger task like #601 

#643 is an even bigger project would require you to first do the backend APIs also.

**Comment by Mogakamo** [comment]
ok thanks for the heads up @daltonfury42. I'll get back when i'm done

**Comment by divyansh21jain** [comment]
Hello @Mogakamo I just saw the list of issues described in the list and would be happy to contribute.

**Comment by maaverik** [comment]
Closing this since it looks like this is all covered.
