### ISSUE TITLE
Prevent page shake on background refresh

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#585]
On the token status page, we periodically call the backend every 10 seconds to check for updates. While this happens, the page gets a loader, and it also shakes up a bit because the loader reduces the size of components.

https://user-images.githubusercontent.com/11256376/111901030-aaf87a00-8a5b-11eb-8cf6-8925fb906965.mov

Wondering what is the best way to handle this. I could think of two ways:

1. Use CSS to make sure the sizes don't change when loader is rendered vs the contect.
2. Show loader only on first load, don't render on subsequent refreshes. 

Thoughts?

**Comment by maaverik** [comment]
Option 2 seems okay. Loaders won't be required once there is some content on the page, so it would be fine to remove them, and it's a simpler change than making CSS changes. 

We could also modify the [getToken.fulfilled] handler in token slice to only change state of the aheadCount is different. I feel like that would be the ideal fix here.

**Comment by maaverik** [comment]
My suggestion won't fix the problem since the LoadingStatus component works based on the pending status of the action provided. So we'll have to somehow show the loader only the first time like you said.

**Comment by daltonfury42** [comment]
we could add a boolean parameter to loading status, `spinOnlyForFirstLoad`. I've never done this, we could try. And then use it such cases.

**Comment by maaverik** [comment]
Do you have any ideas on how to best implement this? The only implementation I could think of is very complicated.

**Comment by daltonfury42** [comment]
I see. I tried running my initial simple idea through my head and got stuck too. Can you try if this will work?

1. A local state variable numTimesPending initially set to 0
2. A useEffect that would listen for changes to the action status and increment each time pending state comes
3. If spinOnlyOnce is set, and numTimesPending > 1, don’t spin
