### ISSUE TITLE
Token Design Is not Correct

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#588]
This is how the tokens should look like, as per our latest design:

![image](https://user-images.githubusercontent.com/11256376/111911667-8668c600-8a8c-11eb-8e5f-bf9dcb3665ce.png)

For for some weird reason, it's looking like this:

![image](https://user-images.githubusercontent.com/11256376/111911698-9aacc300-8a8c-11eb-9682-109c3ccb0f7f.png)

It seems to be some old version of the token component, did we accidentally overwrite something somehow? 🤔

**Comment by maaverik** [comment]
I believe this happened when @mradenovic made the redux changes to the admin page. He created a new delete button with this style. It looked okay to me and I thought you were aware :sweat_smile:.

**Comment by maaverik** [comment]
I believe this happened when @mradenovic made the redux changes to the admin page. He created a new delete button with this style. It looked okay to me and I thought you were also aware :sweat_smile:.

**Comment by daltonfury42** [comment]
![image](https://user-images.githubusercontent.com/11256376/111912216-b4e7a080-8a8e-11eb-95be-9f26d60bc100.png)


I see.. I liked the older one... minor points against our new one:

1. Three buttons in a row look a little redundant, with less variety
2. REMOVE is more explicit and clearer. 

That's when @akashkbaburajan designed the new one:

![image](https://user-images.githubusercontent.com/11256376/111912161-6b975100-8a8e-11eb-959c-50bce86de107.png)

@mradenovic Thoughts?

**Comment by mradenovic** [comment]
Oh, I introduced that change as testing. Ended up in commit. Sorry 😳

**Comment by daltonfury42** [comment]
Yo. No worries, @maaverik has reverted that change manually
