### ISSUE TITLE
Implement Queue History

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#601]
Currently if a token is removed, it's gone for ever from the user's view. We should present the history of deleted tokens in the queue history section on the right side panel.

![image](https://user-images.githubusercontent.com/11256376/113090312-1d5d1d00-9207-11eb-9c1c-79b9ec7d739e.png)

Design: https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/screen/fe137c74-d5e2-4fe1-af85-10877cc560b8/

For now the log can show just added and removed events.

**Comment by daltonfury42** [comment]
Backend call to `GET /queue/<queue-id>`now returns two lists: the existing list of active tokens, and a separate list of removedTokens, with the deletion time stamp. (https://github.com/SimplQ/simplQ-backend/pull/154)

**Comment by Mogakamo** [comment]
How is supposed to be implemented @daltonfury42

**Comment by daltonfury42** [comment]
The UI design is in the link above, and to get the required details, you can take a look at the response of `GET /queue/<queue-id>` call. Let me know if you have any specific questions while implementing.

**Comment by anjali-001** [comment]
Hey @daltonfury42! I would like to work on this issue.

**Comment by Soumit915** [comment]
@daltonfury42 we need to store a list of objects, that will consists of all the events or history of that particular queue in the backend. 

I want to contribute. Can you please guide me, if we can store this info in the backend? Then, I can make a Queue history as you have mentioned above

**Comment by anjali-001** [comment]
Hey @daltonfury42  I have made a PR(#646 ) that fixes this issue. I made a call to `/queue/<queue-id>' route  to get the list of added and removed tokens, however the removed tokens have the tokenCreationTimestamp, so I made appropriate changes to display the queueHistory list. The details of the changes are mentioned in the PR.

**Comment by daltonfury42** [comment]
There seems to be duplication of efforts here. 

I agree with @Soumit915's point [here](https://github.com/SimplQ/simplQ-backend/issues/126#issuecomment-903574236) that it's better to have a dedicated queue history endpoint that would give a list of events that then we can display. 

One way is to merge @anjali-001 's PR, and then @Soumit915 can work on refactoring it to consume the new endpoint, which you can implement in the meantime. 

@Soumit915 What do you think?

**Comment by Soumit915** [comment]
> There seems to be duplication of efforts here.
> 
> I agree with @Soumit915's point [here](https://github.com/SimplQ/simplQ-backend/issues/126#issuecomment-903574236) that it's better to have a dedicated queue history endpoint that would give a list of events that then we can display.
> 
> One way is to merge @anjali-001 's PR, and then @Soumit915 can work on refactoring it to consume the new endpoint, which you can implement in the meantime.
> 
> @Soumit915 What do you think?

@daltonfury42,  I have finished working with this issue in the front-end, only thing that is left is to get the backend support and have the list and then, I can just put the api-values and the issue will be resolved. 

![image](https://user-images.githubusercontent.com/46458047/130669269-52472036-03cd-4949-b7e8-815eea99e4cc.png)

This is the implementation of the front-end part. I have been waiting for your call on the backend issue. For prototype, I am have entered all static values.
