### ISSUE TITLE
Terms of service link on Google sign in page redirects to home page

### ISSUE THREAD

**Issue by jonathanhhoward** [SimplQ/simplQ-frontend#606]
**Describe the bug**
The "terms of service" link on the Google sign in has path `simplq/#terms-ofservice`. This redirects to the home page instead of the terms of service page.

**To Reproduce**
1. On the home page click the "Login" button.
2. On the auth page click the "Continue with Google" button.
3. On the Google sign in page click the "terms of service" link.
4. The browser is redirected to the home page.

**Expected behavior**
The browser should be redirected to the terms of service page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89

**Smartphone (please complete the following information):**

**Additional context**
Hovering over the link shows the intended path is `https://simplq.me/#terms-of-service`. The router is not setup to handle the hash route in the path, so the browser goes to the home page instead.

**Comment by daltonfury42** [comment]
Hi @jonathanhhoward thanks for reporting this. 

Correcting the OAuth consent screen would require a verification from google that would take some days. I've corrected it to https://simplq.me/privacy#terms-of-service
