### ISSUE TITLE
Improve Admin Page Tutorial

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#607]
When a user goes to the admin page when creating his first queue, there is a tour that is shown. This is implemented [here](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/pages/Admin/getTourSteps.jsx).

We currently has two steps:

![image](https://user-images.githubusercontent.com/11256376/115108255-0f402800-9f8d-11eb-89fc-83b6f3ed40e5.png)

![image](https://user-images.githubusercontent.com/11256376/115108282-326ad780-9f8d-11eb-80ea-29d4d09310fe.png)

There are two improvements needed.

1. We need to add a third step to "Print QR Code". 
2. Exiting the tutorial at the end is not very smooth.
3. Exiting anytime in between should be more trivial.

We could explore [this](https://github.com/elrumordelaluz/reactour#laststepnextbutton) and [this](https://github.com/elrumordelaluz/reactour#showclosebutton) etc in [reacttour](https://github.com/elrumordelaluz/reactour), which is the tour library we are using.

**Comment by mav1n** [comment]
I have raised a PR for this.

**Comment by daltonfury42** [comment]
Thanks @mav1n. The PR is good, have added some comments, can you take a look?

**Comment by nme077** [comment]
I would like to tackle this issue, but it looks like it might already be resolved. Is this supposed to be closed?

**Comment by maaverik** [comment]
Hi @nme077,  if I remember correctly, we got the desired functionality in. So, yes, this item can be closed. But if you feel like anything can be improved upon, you can add that here and work on it.

**Comment by daltonfury42** [comment]
Closing this issue, feel free to reopen
