### ISSUE TITLE
Add queue setting to enable and disable queue self join.

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#631]
Add a new check box to enable and disable self join.

Use this PR as a reference: https://github.com/SimplQ/simplQ-frontend/pull/603

Patch request can be send with the boolean field isSelfJoinAllowed

**Comment by iamraki** [comment]
Hi I would like to work on this

**Comment by maaverik** [comment]
@iamraki, have you made any progress on this item?  In case you're not actively working on it, @js-sapphire could take a crack at it. Please let us know.

**Comment by daltonfury42** [comment]
Since we had not head from @iamraki I think you can take this up.

**Comment by js-sapphire** [comment]
Hey @maaverik, @daltonfury42, does this solution work?
