### ISSUE TITLE
Failed to execute 'scrollTo' on 'Window': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#636]
**Describe the bug**
Sentry reported this error:
```
TypeError: Failed to execute 'scrollTo' on 'Window': 2 arguments required, but only 1 present.
  at TypeError (native)
  at De (/static/js/main.3c2e0bb2.chunk.js:1:11798)
  at Ue (/static/js/main.3c2e0bb2.chunk.js:1:11896)
  at os (/static/js/2.740a1ba3.chunk.js:2:1261704)
  at mu (/static/js/2.740a1ba3.chunk.js:2:1280845)
...
(18 additional frame(s) were not displayed)
```

**Additional context**

![image](https://user-images.githubusercontent.com/11256376/117561955-d2adab00-b0b8-11eb-9a84-4e33444992b5.png)

[This](https://github.com/SimplQ/simplQ-frontend/blob/f995055f75ef7b7cd923a416badc872978a52d5a/simplq/src/utils/scrollingOperations.js#L10) is where we are calling this function.

**Comment by maaverik** [comment]
Were you able to reproduce this?
