### ISSUE TITLE
Increase font size for reading purposes

### ISSUE THREAD

**Issue by rahulshawdev** [SimplQ/simplQ-frontend#654]
**Is your feature request related to a problem? Please describe.**
The font size of this section is too small. People with eye problems will have a hard time reading.

**Describe the solution you'd like**
Maybe increase the font size.

**Additional context**
![simplq-increase](https://user-images.githubusercontent.com/82671048/134802989-244aaf22-e4d9-4847-b579-c72d040b17f9.png)

**Comment by maaverik** [comment]
Hi @rahulshawdev, that's a fair ask. Do you want to give this item a try? I think [this](https://github.com/SimplQ/simplQ-frontend/blob/a9ff4f2e97b3c9e3743d22924d1583b0fe3a3632/simplq/src/components/pages/Home/Home.module.scss#L171) CSS class is the one that styles this part.

**Comment by rahulshawdev** [comment]
yeah sure :)

**Comment by daltonfury42** [comment]
Sure, the first PR would be accepted, though. 🏎️ 

Lets also increase to the next level and not too much.
