### ISSUE TITLE
Imporve Queue History on Mobile

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#659]
On desktop / larger screens, queue history (Available once you create a queue and add and remove few people) looks like this:

![image](https://user-images.githubusercontent.com/11256376/135862449-7a78f9f6-ba6a-40d1-a3d3-410a5d79ce69.png)

The bottom doesn't fit on smaller screens. It'll be best of we can flex wrap here:
![image](https://user-images.githubusercontent.com/11256376/135862867-2ff545ab-183e-4c65-9d7c-667231161808.png)

**Comment by joaovictor3g** [comment]
hi @daltonfury42  i would like to solve this problem, could you assign me?
