### ISSUE TITLE
Save Joining Info for later use.

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#675]
It's common for our users to come to the site daily or weekly for getting tokens. It will be helpful for the users to not have to enter their name and mobile number.

![image](https://user-images.githubusercontent.com/11256376/137066311-39dd173a-7c48-4499-9f6a-607cd7f510d0.png)
(https://www.simplq.me/j/adsdsa)

Above the _Join Queue_ button, have a checkbox "Save for later use" that is ticked by default.

1. If enabled, save the name and contact number to local storage on clicking the _Join Queue_ button.
2. If disabled, clear localstorage if it has data on clicking the _Join Queue_ button.
2. If the information is already stored in local storage, prefill the name and contact number on rendering the component for first time.

This is a very easy task, the changes would be fully contained in [this](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/pages/Join/JoinForm.jsx) file.

**Comment by nguyenhung15913** [comment]
Hi, I am interested in this issue. Could you please assign it to me? Thanks.

**Comment by daltonfury42** [comment]
Sure, go ahead. First ready best PR would be accepted. 😆
